ilios/user-guide

- dashboard/calendar-view-options.md
This is the second location where I am updating the guide to advise our week runs from Sunday to Saturday. There may be more of this nature.
> another week duration update

- README.md
More proof of concept stuff really - wanting to merge from my local up to master for the user guide
> trying to do a brief update - adding CAS to readme

- programs/edit-program.md
see title - another one to practice doing this - why I keep creating two PR's I am not sure
> fixed URL for perms matrix in Programs

- courses-and-sessions/sessions/README.md
Fixing a link that was not explained properly.
> Sessions - Update Readme

- glossary.md
Cleaning up the markdown file a bit and updating ILM description in Glossary.
> code cleanup and ILM def update

- learner-groups/sub-groups.md
> quick_text_update_sub_groups

- admin/user-account-and-role-management.md
While the Admin console portion of the user guide is quite out of date and needs revising, the concept of "Current" courses and other objects is not applicable here.
> "Current" not applicable in this context - Admin Console

- admin/add-learners-to-cohort.md
> fix_typo_add_learners_to_cohort

- dashboard/reports.md
> Update and rename my-reports.md to reports.md

- SUMMARY.md
The file name has been updated as well but I am not sure if it is present yet to change the link - changing the title first
> Update SUMMARY.md - update MyReports chapter to Reports

- SUMMARY.md
see title - hopefully I won't have to recreate the whole page and this will sync this back up again
> Update SUMMARY.md - reports.md link

- SUMMARY.md
I updated the summary.md file with a new entry at the highest level called "reports" - I typed in to hopefully create the README.md file but I am not sure if this will work - we'll see - working outside of GitBook
> trying to add a Reports chapter

- SUMMARY.md
> get rid of reports chapter for now

- SUMMARY.md
This is in the reports directory since the directory is currently empty.
> adding a reference to a non-existent README.md

- reports_README.md
adding a file here to be linked with new directory "Reports" or reports in file structure.
> adding README to be used in Reports dir

- courses-and-sessions/README.md
> demoing my current "process"

- reports/README.md
new branch preferred this time
> another screen shot for Reports

- reports/README.md
going to add an image too showing the download dialog box
> update text in Reports

- courses-and-sessions/courses/visualizations.md
see the PR - going to next add a screen shot showing the top of the data table for reference
> Visualizations Objectives Update

- courses-and-sessions/publishing.md
this is on offerings as well - related to #112
> updating some formatting

- courses-and-sessions/offerings/README.md
see above - text added to the introduction of offerings - more info on learning materials included now
> added more info to offerings intro

- dashboard/README.md
Also added a link to the new Reports page for reference.
> Replace Expanded Menu Image

- README.md
banner link update - moved to "images" folder
> updated link to banner

- dashboard/icons-explained.md
a cpl of unnecessary brackets removed in icons_explained.md file
> typos_fixed

- dashboard/README.md
I attempted to make the HTML look more like it should - it was completely unformatted and looked unruly - budget home linting completed.
> HTML_cleanup

- courses-and-sessions/courses/README.md
I had a cpl bad links pointing to the previous image locations - that is fixed here with this PR
> fixed_a_few_image_links

- courses-and-sessions/courses/edit-course.md
There were four unnecessary asterisks before the publication status listing on this page. This PR should fix that.
> removed asterisks hopefully

- courses-and-sessions/courses/edit-course.md
I wanted all of the links and chapters in this section to have a similar format so this PR should add a couple more bold formats to two links here.
> matched bold link format

- courses-and-sessions/courses/edit-objective.md
also fixed a typo - going to move on past this page after this one hopefully
> added_a_cpl_image_titles

- courses-and-sessions/courses/create-new-course.md
foolishly I had forgotten to include the very necessary .png to the end of one of the image names on markdown page `create-new-course.md`- fixed -- image affected -- `images/course_images/new_course_details.png`
> added missing file ext

- courses-and-sessions/courses/edit-course.md
simply removed "The" from the caption for the image listed above - this is part of the cleanup of Courses - page affected - `edit-course.md`
> fixed image caption cohort_selector.png

- courses-and-sessions/courses/attach-learning-materials.md
`images` needs to be `images` not `iamges` - page affected `attach-learning-materials.md` image affected `add_course_LM_3.jpg`
> fixed attach lm typo

- courses-and-sessions/sessions/edit-parent-objective-s.md
I had forgotten to update the links to the new locations and names of these images. This PR fixes that.
> image links fixed edit-parent-objective-s.md

- dashboard/calendar-search-and-filter-options.md
* page updated `dashboard/calendar-search-and-filter-options.md`
* added captions to remaining images without them 
* images already in correct location
> calendar_srch_and_filter added image titles

- dashboard/mobile-devices.md
* page updated `dashboard/mobile-devices.md`
* added caption where one was missing on an image 
* images already in sub-folder
> mobile_devices - added image caption

- admin/user-account-and-role-management.md
* user guide markdown page affected by this PR - `admin/user-account-and-role-management.md`
* made changes to the markdown mostly removing bad characters - hopefully this will look better
This page is pretty outdated and needs to be updated. New ticket maybe for this one will be entered and closed via PR down the road.
> made minor text formatting updates

- admin/user-account-and-role-management.md
Not too much going on with this one - just minor markdown changes to the following page ...
`admin/user-account-and-role-management.md`
> made minor text updates

- admin/school-permissions.md
> deleted admin/school-permissions.md

- programs/add-program-year.md
* user guide markdown page modified by this PR ... `programs/add-program-year.md`
* description added to top of page 
* information added regarding the "rolling over" of program year(s)
This PR fixes #292 - should close the issue.
> updated program year description and page

- courses-and-sessions/courses/edit-course.md
* user guide markdown page involved and affected by this PR ... `courses/edit-course.md`
* added a bit more clarity to Terms and how they are related to, and selected from, Vocabularies.
> updated edit-course definition of terms

- programs/add-program-year.md
* user guide markdown file affected by this PR -- `programs/add-program-year.md`
* added a link to adding Vocabulary Terms to a Session - linked to that 
* closes #120
> added a link to program year for adding terms

- courses-and-sessions/sessions/attach-learning-materials.md
* markdown user guide page affected by this PR ... `courses-and-sessions/sessions/attach-learning-materials.md`
Made a number of formatting and text updates to this page.
> attach_learning_material_update

- courses-and-sessions/courses/README.md
* page affected by this PR ... `courses-and-sessions/courses/README.md`
Added a few more details about Course Year.
> added_more_detail_to_course_year_desc

- courses-and-sessions/courses/edit-course.md
just a quick text update on `courses-and-sessions/courses/edit-course.md`
> added_more_detail_to_course_year_edit

- programs/add-program-year.md
> added more info about expanding PY objective details

- reports/reports.md
* branch name is a bit misleading - page affected by this PR is actually `reports/reports.md` not `README` - it looks like I opted to rename the main page in this case. 
* I found an image with `png.png` in the ref link - won't work - fixed it here
> fixed a typo in reports.md file

- programs/add-program-year.md
* page involved with this PR ... `programs/add-program-year`
fixes #342
> added a bit more info about prog year linking

- courses-and-sessions/offerings/edit-offering.md
* page modified with this PR ... `courses-and-sessions/offerings/edit-offering.md`
I was planning on closing issue 83 with this PR but a bit more information is still lacking.
> more info on learner group selection

- README.md
Page updated `README.md` at root level - this is the introduction to the guide. Removed an outdated bit of information hinting at the existence of other user guides - no need for this.
> removed outdated reminder info

- dashboard/README.md
* page updated `dashboard/README.md`
updated the links available and default view options
> updated dashboard initial links

- dashboard/icons-explained.md
page modified ... `dashboard/icons-explained.md` - updated/truncated the opening spiel a bit to simplify it and hopefully not confuse the reader
> updated dashboard/icons-explained.md

- courses-and-sessions/courses/visualizations.md
* Page involved in this PR ... `courses-and-sessions/courses/visualizations.md`
There was a no longer valid disclaimer about how more information was forthcoming. The information is already there so this disclaimer can be removed and will be via this PR.
> removed text no longer needed

- dashboard/event-detail-view.md
This just cleans up a bit on what I was working on before - previous PR. Still need to either explain here or elsewhere about the Learning Material check activity boxes and how they work.
> event detail update - more to come

- dashboard/event-detail-view.md
Text descriptions added to `dashboard/event-detail-view.md` - images coming soon to show the various check box state.
> event detail update - added text detail about LM check boxes

- dashboard/event-detail-view.md
- dashboard/materials-view.md
* pages modified in this PR ...
* `dashboard/materials-view.md`
* `dashboard/event-detail-view.md`
There is a follow up PR coming after this one is merged to generate a link to demonstrate the Learning material activity check boxes.
> a few formatting improvements to generate needed links

- dashboard/materials-view.md
* modified:  ` dashboard/materials-view.md`
* link added so user will be routed to event detail where there is more available information on the check box states
> updated link to activity check boxes

- dashboard/materials-view.md
* page modified `dashboard/materials-view.md`
* text updated to better reflect updated image from #377
> updated text description to match new image better

- courses-and-sessions/courses/add-parent-objective.md
```
modified:   courses-and-sessions/courses/add-parent-objective.md
```
> updated text explaining parents of course objectives

- dashboard/README.md
`modified:   dashboard/README.md`
I cleaned up some unnecessary characters and fixed up some header levels to read better for the user - the whole `On this page` thing - easier navigation - going to be cleaning this up in many places like everywhere starting with this one.
> dashboard README update - chapters and cleanup

- dashboard/calendar-view-options.md
`modified:   dashboard/calendar-view-options.md`
I updated the "on this page" link on ^^^ to be a little more reader-friendly.
> updated on this page link for mult offerings display

- courses-and-sessions/courses/README.md
`modified:   courses-and-sessions/courses/README.md`
This is an attempt to make the page flow better using `On This Page` indentation in the side margin.
> updated on this page indentations README courses

- dashboard/search.md
`modified:   dashboard/search.md`
I made the "On This Page" headers a bit more prominent in case later on indentations and more content might be required. Changed to H2 rather than H3.
> updated on this page indentations global search

- dashboard/calendar-view.md
`modified:   dashboard/calendar-view.md`
Increased size of "Calendar" header to make indentation flow better on "On This Page" area over to the right side of the screen.
> updated on this page indentations calendar view

- dashboard/event-detail-view.md
`modified:   dashboard/event-detail-view.md`
This is an effort to make the "Event Detail View" flow better and have better indentation and format - need to check once merged to make sure this helps improve the page.
> updated on this page indentations event detail

- dashboard/calendar-search-and-filter-options.md
`modified:   dashboard/calendar-search-and-filter-options.md`
* updated a bunch of the headers to make the page flow better 
* removed some unnecessary characters from the markdown file
> updated on this page indentations cal srch and filter

- courses-and-sessions/courses/README.md
`modified:   courses-and-sessions/courses/README.md`
This is part of the ongoing effort to make pages flow better and have better indentation and navigation using the "On this Page" section on the right of the screen for navigation.
> updated on this page indentations course README

- dashboard/event-detail-view.md
`modified:   dashboard/event-detail-view.md`
I changed one of the captions for more clarity and navigation purposes.
> updated on this page indentations event detail view

- dashboard/my-profile.md
`modified:   dashboard/my-profile.md`
I added quite a few details to the above-mentioned page. The read-only attributes are explained in more detail. The headers are updated and sized for better reading as well - the "On this Page" business.
> added a bunch more info onto this page

- dashboard/language-selector.md
`modified:   dashboard/language-selector.md`
Simplified the text description used on this page.
> removed some reduntant text from this page

- dashboard/mobile-devices.md
`modified:   dashboard/mobile-devices.md`
Modified a bit of text on the above-referenced page and set up some chapters to be included in the "on this page" navigation.
> set up chapters for on this page and modified a bit of text

- courses-and-sessions/courses/edit-course.md
`modified:   courses-and-sessions/courses/edit-course.md`
I shortened and clarified a couple of the headers to read better for navigation purposes and "On this Page" functionality.
> updated a cpl headers to be more readable in TOC

- courses-and-sessions/courses/course-leadership.md
`modified:   courses-and-sessions/courses/course-leadership.md`
* indentations fixed up for better page navigation
* added image captions to many images that were missing
* slight page markdown clean-up
> modified page for better navigation and image captions

- courses-and-sessions/courses/add-parent-objective.md
` modified:   courses-and-sessions/courses/add-parent-objective.md`
On the above page, I changed a numbered list to a series of ###'s instead but the caveat is that the numbered list was manually numbered so I decided to keep the numbers in there too. 
I plan on doing a visual review of this once merged to see this is preferable to simply removing the numbers (1., 2. etc.)
> upgraded numbered list to ###

- courses-and-sessions/offerings/README.md
`modified:   courses-and-sessions/offerings/README.md`
Closes #386 - see title and ticket for details
> included a link to multi-day offerings on README.md

- courses-and-sessions/courses/edit-parent-objective.md
`modified:   courses-and-sessions/courses/edit-parent-objective.md`
* description added towards top of page 
* image caption modified 
* headings added for navigation
> updated navigation and markdown course parent obj

- dashboard/home.md
`modified:   dashboard/home.md`
I noticed the highly formatted HTML images on this page were missing ALT tags - added them with this PR.
> added some ALT tags to images

- courses-and-sessions/courses/sort-objectives.md
`modified:   courses-and-sessions/courses/sort-objectives.md`
* fixed up introduction to contain more information and not be redundant 
* set up some chapter bookmarks to aid in navigation of the page
> updated introduction and set up chapter headings

- README.md
`modified:   README.md`
This one may be reverted or undone or modified as I am trying something new here. A URL link to our iliosproject.org/about section was added to the introduction to the page - this may not work as it looks kind of weird.
> README.md updated with introduction and link to Ilios info

- README.md
`modified:   README.md`
This is introductory `README.md` for the whole application and user guide. The root page for the guide ...
https://iliosproject.gitbook.io/ilios-user-guide/
I tried putting a URL link in the introduction section but it didn't work the way I was hoping. Related to #445 in that sense and updating around that one since I am not quite understanding why the URL won't work in the "introduction".
> README.md updated with introduction and link to Ilios info 2nd try

- README.md
`modified:   README.md`
Who knows about this one? I am testing some stuff about headers, navigation, introduction - this is a test not a fix
> README.md testing stuff - may undo

- README.md
`modified:   README.md`
Wondering if the word "Introduction" will even appear anywhere. I may stick with this for now but again this is more for testing than fixing. Trying to figure some stuff out here.
> README.md testing stuff - again may undo or modify

- README.md
```
On branch remove_unnecessary_header_intro_to_guide
```
This one is purely for testing only and will be quickly undone.
> README.md testing stuff - will undo for sure

- README.md
modified:   README.md`
There may two commits on this one.
> Fixing previous testing pr

- courses-and-sessions/courses/course-rollover.md
```
On branch course_rollover_chapter_fixes
```
As title indicates, this PR updates the chapter titles for clearer navigation, adds an additional "H1" markdown style to help with this, updates image captions, and adds and edits the markdown.
> added one chapter and updated other titles plus text

- courses-and-sessions/courses/attach-learning-materials.md
```
On branch work_on_attach_learning_materials
```
> markdown cleanup and chapter updates

- courses-and-sessions/courses/attach-learning-materials.md
```
On branch add_intro_to_attach_learning_materials_course
```
* added an introduction section to the page listed above 
* cleaned up markdown a bit more
> adding an intro to attach course learning materials

- courses-and-sessions/sessions/add-new-session.md
```
On branch promote_headers_and_markdown_update
```
* cleaned up some more stuff
> cleaned up markdown add new session

- courses-and-sessions/sessions/README.md
```
On branch promote_session_list_header
```
Improved navigation - the Session List needed to be larger to be included in the "On this Page" navigation.
> promoted session list header to ### better nav

- courses-and-sessions/sessions/independent-learning-module-ilm.md
```
On branch fix_up_ilm_chapters
modified:   courses-and-sessions/sessions/independent-learning-module-ilm.md
```
> made a couple quick chapter changes ILM

- courses-and-sessions/sessions/independent-learning-module-ilm.md
```
On branch one_more_chapter_hierarchy_fix_sessions_ILM
modified:   courses-and-sessions/sessions/independent-learning-module-ilm.md
```
> updated chapter heading settings - ILM

- programs/README.md
```
On branch fix_quick_typo_extra_chars_in_program_read_me
modified:   programs/README.md
```
* updated one of the headings 
* deleted a bit of misleading text 
* removed some bogus characters
> a few text changes in README.md - programs

- permissions.md
```
On branch update_permissions_add_student_advisor_info
```
> a few minor modifications to permissions - add student adv info

- learner-groups/sub-groups.md
```
On branch update_permissions_add_student_advisor_info
```
Oops I am on the wrong branch - the name is not correct - I hope this works out fine. I will delete this branch after merge.
> a cpl minor changes to sub groups page

- learner-groups/README.md
not sure what exactly if anything will be in this - I forgot to do `add .` before making the commit - let's see eh?
> updating chapters in README for learner groups

- programs/edit-program.md
```
On branch promote_to_headers_chapters_in_programs
modified:   programs/edit-program.md
```
Updated "On this Page" navigation to include headers for chapters - better navigation on page.
> chapters to become headers - better nav

- README.md
```
On branch fix_introduction_to_guide_one_more_cut
```
* had to trim this a bit more to fit correctly
> one more text trim on guide intro

- dashboard/search.md
```
On branch promote_filter_by_year_school
```
> upgrading filter by school by year

- dashboard/README.md
```
On branch add_more_info_about_mobile_view
```
> added link and chapter reference about mobile view

- dashboard/calendar-feed-options.md
```
On branch more_mobile_device_updates_cal_feed_options
modified:   dashboard/calendar-feed-options.md
```
The branch name is slightly off what actually was modified. I ended up adding a (an) H3 ### for deploying the LTI instead of more mobile device updates. That is covered and linked adequately on the page already.
> added H3 for deploying LTI

- instructor-groups/README.md
- instructor-groups/delete-instructor-group.md
```
On branch add_content_to_new_page
modified:   instructor-groups/README.md
modified:   instructor-groups/delete-instructor-group.md
```
I might be getting out of sync here (and I hope not). I had added some changes that didn't take because I had already merged the previous PR and could no longer add to it. I may have deleted the branch from here but was still using it locally. Anyway, I created a new branch and re-did the changes (different changes since the old ones are queued up somewhere maybe but weren't retained). Hopefully there won't be a conflict.
> re-added a few details plus navigation to newly created page

- SUMMARY.md
```
On branch fix_TOC_to_point_to_new_page_delete_instructor_group
```
> added link in TOC to new page delete instructor group

- courses-and-sessions/offerings/create-single-offering.md
```
On branch add_chapters_to_single_offerings_page
modified:   courses-and-sessions/offerings/create-single-offering.md
```
Navigation improvements for `courses-and-sessions/offerings/create-single-offering.md` - chapters and bookmarks updated.
> improved navigation on offerings single offering

- schools/vocabularies.md
```
On branch set_up_chapters_school_vocabularies
modified:   schools/vocabularies.md
```
> set up a few more bookmarks for better navigation

- courses-and-sessions/courses/visualizations.md
```
On branch remove_unnecessary_chapter_level
```
I will want to check this again but for now I removed a # (H1) heading that was being superseded by page definition apparently.
> removed a # header that wasn't appearing anyway

- admin/user-account-and-role-management.md
```
On branch fix_typo_in_user_acct_and_role_mgmt
modified:   admin/user-account-and-role-management.md
```
> quick typo fix - acct and role mgmt

- admin/user-account-and-role-management.md
```
On branch update_user_acct_and_role_mgmt_disable_acct
modified:   admin/user-account-and-role-management.md
```
* updated the process for setting an acct to be inactive - the instructions were outdated probably from v2
* fixed a few chapters to the correct level 
* fixed a few typos
> a cpl more markdown fixes - acct and role mgmt

- README.md
```                                        
On branch replace_starting_point_with_welcome
```
> updating a caption welcome to Ilios

- README.md
```
On branch add_chapter_for_signup_info
```
> chapter added on sign up for email updates

- README.md
```
On branch add_chapter_for_signup_info_rearrange
```
> moved main image to proper location

- additional-information/README.md
```
On branch add_link_to_FAQ
modified:   additional-information/README.md
```
> added link to FAQ - additional information

- courses-and-sessions/publishing.md
```
On branch update_main_publishing_course_image
modified:   courses-and-sessions/publishing.md
```
> minor text change - need to refresh branches

- courses-and-sessions/publishing.md
```
On branch update_number_references_crs_pub_options
modified:   courses-and-sessions/publishing.md
```
> updated text course publication - numbered refernces added

- glossary.md
```
On branch update_cohort_glossary_decription
```
The Cohort example in here had a graduation date of 2017 - updated to 2027, our current cohort in reality.
> updated cohort description in glossary - way outdated

- schools/school-leadership.md
```
On branch quick_change_to_school_level_leadership_desc
modified:   schools/school-leadership.md
```
Made a few chapter updates - images and further changes coming soon.
> made a cpl quick updates to leadership - school level

- schools/school-leadership.md
``` 
update_to_match_new_leadership_desc
modified:   schools/school-leadership.md
```
Just updating the page a bit to match the new text style of describing "leadership" at the school level.
> few more text updates school-leadership.md

- schools/school-leadership.md
```
On branch put_permissions_link_into_leadership_school_level
modified:   schools/school-leadership.md
```
The word salad is me trying to explain along with a link to the permissions model the difference between a director and an administrator. I might edit this down later. The salad seems fine actually upon reviewing the PR. I prefer Bleu Cheese dressing though.
> permissions added along with word salad

- reports/reports.md
```
On branch update_description_run_reports_unsaved
```
Edited the markdown page referenced above to include sections H3 ### on the page. New section added for "on the fly" report running - mentioned it at least - more details coming soon.
> adding create new report page section

- reports/reports.md
```
On branch fix_reports_bookmarks
```
Getting some areas with bookmarks ready to use for screen shot and details forthcoming about creating an ad-hoc report and not saving it vs. creating and saving a report for future use.
> adding create new report page sections

- reports/reports.md
```
On branch describe_first_level_report_options
```
The above file was indeed modified. I added a list of all of the available report building options - top-level after school selection.
> added list of available report selections top-level

- reports/reports.md
> fixed level of new report options back to H2

- reports/reports.md
```
On branch need_to_figure_out_what_is_happening
```
I was having some `overwrite` issues due to some PR issues - it was weird - hopefully this will clean everything up
> one more change to refresh

- reports/reports.md
```
```
Added a brief description that in order to download data, the report must first be saved and accessed via saved report.
> reports update download requirements

- reports/reports.md
```
On branch fix_typo_in_ad_hoc_reports_section
```
Fixed typo on above-mentioned markdown page.
> reports update fixed typo

- dashboard/event-detail-view.md
```
On branch new_chapter_in_event_detail_objective_listings
modified:   dashboard/event-detail-view.md
```
> added chapter and description to obj listings event detail

- reports/reports.md
```
On branch include_download_data_chapter_reports
```
> added chapter H3 style for download of report data

- courses-and-sessions/offerings/create-single-offering.md
```
On branch update_single_offering_description
modified:   courses-and-sessions/offerings/create-single-offering.md
```
> added description of single offering at top of chapter

- courses-and-sessions/offerings/create-small-group-offerings.md
```
On branch update_small_group_offering_description
```
> added description of small group offering at top of chapter

- reports/reports.md
```
On branch get_rid_of_download_in_unsaved_report_ref
```
> removed reference to dowload data - unsaved report

- programs/add-program-year.md
- programs/competency-map-download.md
```
On branch fix_naming_toggle_not_light_bulb_py_objectives
modified:   programs/competency-map-download.md
```
> toggle not light bulb for py objectives

- courses-and-sessions/courses/edit-objective.md
```
On branch decrease_edit_description_size
```
> edit course objective description updated and header size too

- courses-and-sessions/courses/edit-objective.md
```
On branch try_header_changes_to_sort_out_page_structure
```
Not sure if these changes will stand the test of time but I wanted to see about making this page have better navigation and clearer access to the included information. Hopefully this will work out - if not, more updates may be forthcoming.
> made a bunch of formatting changes to headers

- courses-and-sessions/sessions/edit-session.md
```
On branch fix_manage_terms_link_session_edit_2
```
Fixes #609
> fixing link to manage term(s) - session edit

- dashboard/week-at-a-glance.md
```
On branch try_bold_for_check_box_states_WaaG
modified:   dashboard/week-at-a-glance.md
```
Just setting a couple of formerly numbered and badly formatted items to **bold** setting.
> setting bold on check box states - WaaG page

- courses-and-sessions/courses/create-new-course.md
```
On branch fix_double_header_create_new_course
modified:   courses-and-sessions/courses/create-new-course.md
```
> attempt at fixing duplicate headers

- courses-and-sessions/courses/README.md
```
On branch try_to_group_and_bold_better_course_readme
```
I was hoping to get actual bullet points on my UL lists but we'll see. This may again get reformatted if need be.
> course readme update - bolds and sections

- courses-and-sessions/courses/README.md
```
On branch add_asterisk_for_sessions_chapter_course_readme
```
wrong branch name again - phooey - colon added not asterisk - anyway minor but necessary change to course readme.md
> not asterisk - colon - added to sessions list item on course readme

- courses-and-sessions/courses/README.md
```
On branch add_link_to_session_list_from_course_README_fix
Your branch is up to date with 'origin/add_link_to_session_list_from_course_README_fix'.
```
> added link to sessions main page from course README fix

- courses-and-sessions/courses/README.md
```
On branch update_sections_caption_and_headings_course_README
```
Making page a little bit clearer as far as the three main areas are concerned on this page.
> renamed sections to functional areas and updated desc

- courses-and-sessions/courses/README.md
trying to get some bullet point or dash indicators on a list - this is for the heading section of the course README - if this either doesn't work or looks worse, I will revert it
> heading area course README another attempt at dashes or bulletpt

- README.md
removed coloring that made some headers look like links - left one in green shading just to see - will probably remove that one too after this test - it's easier to see in design mode although so much black font makes me feel the guide is yelling at me - but it isn't
> got rid of blue looking like link heading but left one green

- README.md
got rid of the last green coloring tag on one of the headers (markdown H2 = ##) -- here is the code I got rid of - keeping for future reference in case I find a good color to distribute throughout the guide -
> got rid of green one now too

- courses-and-sessions/courses/README.md
```
On branch update_course_title_description
```
> updated upper description of course title / name

- courses-and-sessions/courses/README.md
```
On branch remove_goofy_dashes
```
> quick final test before removing goofy dashes

- courses-and-sessions/courses/README.md
```
On branch remove_goofy_dashes_for_real_giving_up_on_bulpts_for_now
```
> goofy dashes removed indentations fixed

- courses-and-sessions/courses/README.md
```
On branch remove_punctuation_unnecessary_period
```
> noticed a typo I wanted to fix

- courses-and-sessions/courses/README.md
```
On branch one_more_test_asterisk_bullet_point
```
this will probably not be kept as is but I wanted to see how it looks - extra asterisk attempting to create bullet point - probably will be reverted soon
> this is a test and will probably be reverted soon

- courses-and-sessions/courses/README.md
```
On branch one_more_test_asterisk_bullet_point
```
> this is to revert the previous failed test

- courses-and-sessions/courses/README.md
```   
On branch remove_extra_vertical_space
```
> tinkering with vertical space heading alignments

- courses-and-sessions/courses/README.md
```
On branch review_missing_items_text_string_trim
```
removed a bit of text for style consistency purposes
> another text cleanup README courses

- courses-and-sessions/courses/README.md
```
On branch add_course_heading_to_title_definition
```
> fixed indentation - added link - README - courses

- courses-and-sessions/courses/README.md
```
On branch correct_max_length_course_id_field
```
> fixed description - added link - README - courses

- courses-and-sessions/courses/README.md
```
On branch update_detail_header_description
```
I wasn't happy with the formatting of the description of detail on the course README - this PR fixes that.
> fixed description of detail in header

- courses-and-sessions/courses/README.md
```
On branch update_detail_header_indentations
```
This PR has been created to make sure the indentations of the detail header match the other sections.
> fixed indentation of detail to match other sections

- courses-and-sessions/courses/README.md
```
On branch add_details_link_to_course_lms_README
```
> added link learning materials course README

- courses-and-sessions/courses/course-leadership.md
```
On branch rename_course_leadership_to_leadership
```
> changed caption on page to leadership - removed one header

- courses-and-sessions/courses/course-leadership.md
```
On branch update_leadership_description_course
```
> changed some header levels in leadership course level

- courses-and-sessions/courses/course-leadership.md
```
On branch move_removal_of_leadership_description
```
I had the description of the removal of leadership process in the wrong location. This PR fixes that.
> moved remove leadership description to correct location

- additional-information/mesh/README.md
Added a link to a sub page - add MeSH to course objective.
> first add link to add MeSH to course

- additional-information/mesh/add-mesh-to-session-objective.md
```
On branch add_new_sub_page_MeSH_to_session_new_branch
new file:   additional-information/mesh/add-mesh-to-session-objective.md
```
> new file added add MeSH to session objective page

- SUMMARY.md
I added a page to the guide in the previous PR #677 - this adds the link in the TOC (summary.md) to point to this newly created page.
> updated toc summary file to include new page

- courses-and-sessions/courses/attach-learning-materials.md
```
On branch rearrange_course_lm_pages_in_SUMMARY_and_add_new_one
new file:   courses-and-sessions/courses/learning_materials.md
```
This PR mostly does the second part of this branch title - it adds the new file. I'm going to do the linking and reorganization with the next PR.
> added learning-materials.md file first before linking

- courses-and-sessions/sessions/add-session-objective.md
```
On branch session_objectives_new_main_page
modified:   courses-and-sessions/sessions/add-session-objective.md
```
> added final step number 7 to add new session obj

- courses-and-sessions/sessions/add-session-objective.md
```
On branch update_session_add_objective_page
modified:   courses-and-sessions/sessions/add-session-objective.md
```
> made steps into headings rather than numbered list

- courses-and-sessions/courses/README.md
```
On branch rename_print_course_summary_to_course_summary
```
Renamed the hyperlink basically to `course summary` since the "print" aspect of it is already in the description and realistically if you're going to "print" this, you better have a lot of paper and ink.
> updated description in README.md course summary

- schools/session-types.md
```
On branch update_disabled_session_type_desc
modified:   schools/session-types.md
```
> updated session type description in schools/session-type.md

- SUMMARY.md
- programs/README.md
```
On branch investigate_bad_link_program_year_visualization
modified:   programs/README.md
```
> added missing page from busted link

- admin/user-account-and-role-management.md
```
On branch fix_typos_from_previous_PR
modified:   admin/user-account-and-role-management.md
```
Related to #715 - updated the text a bit to fix a typo and make a clarification in the text
> updated cohort assignment process in admin console fixed typo

- courses-and-sessions/sessions/edit-session-objective.md
```
On branch improved_formatting_edit_session_obj
```
Re-formatting the area where I just replaced the images in #717 - bolds instead of indented non-bullet bullets.
> bullet point not working out - replaced with bold

- courses-and-sessions/sessions/edit-session-objective.md
```                                                      
On branch redo_chapters_edit_session_obj
```
> created a bunch of H3 headers for better flow

- courses-and-sessions/sessions/edit-session-objective.md
```                                                      
On branch redo_chapters_edit_session_obj
```
> removed a and the from H3s

- courses-and-sessions/sessions/edit-session-objective.md
```                               
On branch get_rid_of_caption_capitals
```
> updated edit-session-objective.md got rid of CAPs in image captions

- courses-and-sessions/sessions/learning_materials.md
```
On branch create_course_learning_materials_main_page
new file:   courses-and-sessions/sessions/learning_materials.md
```
New page added to the guide - this will make sure that session learning materials has sub pages in the same manner that course learning materials does.
> added new main learning materials page - sessions

- courses-and-sessions/offerings/recurring-event.md
```
On branch recurring_events_make_headers
modified:   courses-and-sessions/offerings/recurring-event.md
```
> added heading chapters to recurring event page

- courses-and-sessions/offerings/recurring-event.md
```                                                   
On branch update_text_description_create_recurring_event
modified:   courses-and-sessions/offerings/recurring-event.md
```
> added a bit more description to recurring event page

- courses-and-sessions/sessions/README.md
- glossary.md
* updated text description of "session" in both session README and glossary.md file
> updated session description in glossary and README

- courses-and-sessions/sessions/README.md
```                                                
On branch replace_one_instance_of_pre_work
Changes not staged for commit:
```
> updated definition of pre_work - prerequisite instead

- courses-and-sessions/sessions/add-new-session.md
```
On branch add_link_to_session_description
```
> added link to glossary definition of session

- courses-and-sessions/sessions/add-new-session.md
```                                         
On branch explain_first_step_add_session_better
```
> updated entry process for adding new session - step one

- instructor-groups/README.md
- instructor-groups/add-instructor-group.md
```
On branch add_school_to_instructor_group_description
modified:   instructor-groups/README.md
modified:   instructor-groups/add-instructor-group.md
```
> updated instructor group description to include school level

- instructor-groups/add-instructor-group.md
```
On branch for_the_sake_of_demonstration_added
modified:   instructor-groups/add-instructor-group.md
```
> updated add instructor - a bit of context

- instructor-groups/edit-instructor-group.md
```
On branch for_the_sake_of_demonstration_added
modified:   instructor-groups/add-instructor-group.md
```
> updated explanation of associated courses

- courses-and-sessions/sessions/README.md
```
On branch update_pre_work_to_prereq_description
```
> pre-work - prerequisites conversion

- SUMMARY.md
```
On branch caption_match_admin_chapters
```
> updated link and caption to match

- programs/edit-program.md
```
On branch fix_update_program_links
modified:   programs/edit-program.md
```
I found some bad links that had been updated page-wise but the links were outdated. This PR fixes that issue.
> fixed bad links in edit-program page

- courses-and-sessions/courses/add-objective.md
```
On branch add_objective_to_course
modified:   courses-and-sessions/courses/add-objective.md
```
> added a couple headings to add course obj page

- courses-and-sessions/courses/add-objective.md
```                                       
On branch add_objective_to_course_caption_fix
modified:   courses-and-sessions/courses/add-objective.md
```
> minor changes made to headings - add course obj

- CODE_OF_CONDUCT.md
- README.md
- glossary.md
- permissions.md
Fixed some MarkdownLint and formatting issues in the root level documentation files.
> fix markdownlint and formatting issues

- programs/edit-program.md
```
On branch check_edit_mode_new_program
modified:   programs/edit-program.md
```
> bad link - missing image - fixed

- README.md
- dashboard/search.md
```
On branch update_global_search_permissions_description
```
> Update global search permissions description

- README.md
```
On branch remove_unneeded_banner_caption
```
> caption banner not needed - removed

- instructor-groups/README.md
```                             
On branch fix_unneeded_capitalization
modified:   instructor-groups/README.md
```
> updated instructor groups text

- admin/maintain-user-record.md
```
On branch update_heading_change_cohort_assignment
modified:   admin/maintain-user-record.md
```
> made a few updates to admin page

- courses-and-sessions/README.md
```                                               
On branch remove_redundant_in_ilios_text
modified:   courses-and-sessions/README.md
```
> remove redundant in ilios text

- glossary.md
```
On branch edit_vocabulary_desc_in_glossary
```
> updated vocabulary description in glossary

- courses-and-sessions/courses/edit-course.md
```
On branch add_course_rollover_link
```
> added link - updated caption

- courses-and-sessions/courses/edit-course.md
```
On branch add_visualizations_link
```
> added link to course visualizations

- courses-and-sessions/courses/edit-course.md
```
On branch fix_course_detail_links
```
> added and cleaned up a few more links

- courses-and-sessions/courses/competencies.md
- courses-and-sessions/courses/vocabulary_terms
- courses-and-sessions/courses/vocabulary_terms.md
```
On branch course_chatpers_setup_competencies_and_terms
new file:   courses-and-sessions/courses/competencies.md
new file:   courses-and-sessions/courses/vocabulary_terms
```
> added place-holder files for future chapters

- courses-and-sessions/courses/competencies.md
```
On branch more_work_on_competencies_course_level_continued
```
> added a bit more descriptive text on competency display

- courses-and-sessions/courses/add-objective.md
```
On branch explain_how_no_offerings_no_graph_course_obj_viz
modified:   courses-and-sessions/courses/add-objective.md
```
> added more info on course obj viz

- dashboard/home.md
```
On branch replace_home_image
modified:   images/dashboard_home/home_link.png
```
> added locational reference text desc to home

- dashboard/README.md
* upgraded link to "also available ..." to H3 for navigational improvement
* put a link to an existing image - re-used it even though it is stored in a different directory - I think this should be fine
* updated text a bit as well.
> added a bit more text for description of help link

- dashboard/README.md
* work in progress possibly this area but 
* put in a dash to match formatting of other menu items
* added to add a horizontal page break for page flow purposes 
* fixed up the text a bit too
> cleaned up a bit user guide link

- dashboard/README.md
```
On branch move_link_to_language_selector_up
```
* removed outdated comment 
* moved link up to more appropriate location
> Move link to language selector up

- dashboard/README.md
```
On branch update_ilios_menu_caption
```
> added flyout language to Ilios menu captions

- dashboard/README.md
```
On branch one_more_update_ilios_flyout_menu
```
> added flyout language to Ilios menu captions update

- dashboard/README.md
```
On branch update_ilios_expander_definition
```
> added a bit more here to clarify

- dashboard/README.md
- dashboard/icons-explained.md
```
On branch remove_now_from_ics_feed_desc
```
> a few more text tweaks on dashboard pages

- learner-groups/edit-group-properties/README.md
```
On branch replace_filter_for_group_with_by_group_title
```
> filter by group title instead of filter for group

- dashboard/README.md
```
On branch fix_dashboard_README
```
> trying to reduce unneeded vertical spacing

- dashboard/search.md
```
On branch test_caption_stuff_and_vert_spacing
```
> added a comment to an image to hopefully fix vert space issue

- dashboard/search.md
```
On branch remove_one_line_and_update_comment
```
> updated comment - still testing vert space issue

- dashboard/search.md
```
On branch oops_undoing_last_change_made_things_worse
```
> undoing previous PR - vert space adjustment

- learner-groups/edit-group-properties/README.md
```
On branch fix_capitaliztions_and_remove_image_edit_LG
```
> removed unneeded image and lower a few Capital letters

- learner-groups/README.md
```
On branch update_description_for_sg_toggle_in_lg_cal
modified:   learner-groups/README.md
```
> added additional information on sub grps toggle lg cal

- learner-groups/edit-group-properties/README.md
Rearranged the page to flow a bit better hopefully ...
```                           
On branch rearrange_lm_membership_page
Changes staged for commit:
```
> rearrange page - edit group properties LM README

- learner-groups/edit-group-properties/README.md
```
On branch update_screen_elements_learner_group_edit
```
> broken link fixed - slight text modification

- learner-groups/edit-group-properties/README.md
```
On branch change_heading_duplicate_of_group_membership
```
> heading caption changed to be more accurate

- learner-groups/edit-group-properties/edit-group-membership.md
```
On branch update_one_to_single_learner_better_header
modified:   learner-groups/edit-group-properties/edit-group-membership.md
```
> updated one learner to read individual learner

- learner-groups/group-assignment-tool.md
```
On branch fix_parent_group_name_learner_upload
```
> fixed parent group name - upload tool

- learner-groups/group-assignment-tool.md
```
On branch one_final_edit_for_now_lg_group_tool
```
> one more bit of editing

- learner-groups/group-assignment-tool.md
```                                                
On branch edit_confirm_save_above_vs_previous_section
```
> quick change group assignment tool

- learner-groups/sub-groups.md
```
On branch remove_redundant_sentence_sub_groups
modified:   learner-groups/sub-groups.md
```
> unneeded and unhelpful duplicate sentence removed

- learner-groups/remove-learner-group.md
```
On branch add_comment_about_learner_group_removal
modified:   learner-groups/remove-learner-group.md
```
> added comment about removing learner groups

- learner-groups/remove-learner-group.md
```
On branch update_red_arrow_comment
modified:   learner-groups/remove-learner-group.md
```
> removed inaccurate comment

- learner-groups/copy-learner-group.md
Made a quick change to the text description regarding the splash screen.
> replaced third image and added text - minor tweak here

- learner-groups/learner-group-defaults.md
```
On branch fix_default_instructor_caption
modified:   learner-groups/learner-group-defaults.md
```
> fixed caption -  default instructor start

- learner-groups/learner-group-defaults.md
```
On branch one_more_caption_update_default_instructors
modified:   learner-groups/learner-group-defaults.md
```
> updated a bit of text for clarity

- schools/README.md
```
On branch update_leadership
modified:   schools/README.md
```
Updated chapter link to match chapter title here.
> minor text update leadership rather than school leadership

- instructor-groups/add-instructor-group.md
```
On branch promote_add_instructors
modified:   instructor-groups/add-instructor-group.md
```
> add instructors to instructor group promoted

- instructor-groups/delete-instructor-group.md
Added description to the deletion of instructor groups - can have members or not - the key is activity.
> remove instructors group desc added

- dashboard/calendar-view.md
```
On branch multi_day_only
modified:   dashboard/calendar-view.md
```
> ILM and linked events covered elswwhere not correct here

- dashboard/calendar-search-and-filter-options.md
```
On branch update_view_switcher_calendar_image
modified:   dashboard/calendar-view-options.md
modified:   images/calendar_view_images/duration_switcher.png
```
This PR updates the description of what Course Administrators and Course Directors see on the Calendar. More details are forthcoming but this sets the stage for that and is an improvement over what was here previously on that topic.
> a cpl of text updates as prelim to new chapters on new filters

- dashboard/calendar-search-and-filter-options.md
```
On branch add_all_events_image
new file:   images/calendar_srch_images/all_school_events_week_view.png
```
> added a spiel about moving to different years

- dashboard/calendar-search-and-filter-options.md
```
On branch remove_most_of_misleading_section_on_calendar_options
```
> cleared up description of selecting criteria for calendar

- dashboard/calendar-search-and-filter-options.md
```
On branch trim_some_more_old_stuff_calendar_filters
```
> trimmed some more stuf out of calendar filters

- dashboard/all_events.md
```
On branch move_all_events_up_a_level
new file:   dashboard/all_events.md
```
No interface changes with this PR ... yet.
> all_events page added to root level of dashboard

- dashboard/all_events.md
- dashboard/my_schedule.md
```
On branch add_my_schedule_page_to_dashboard
modified:   dashboard/all_events.md
new file:   dashboard/my_schedule.md
```
> my_schedule page added to root level of dashboard

- SUMMARY.md
```
On branch link_new_page_all_events
```
> all_events page now linked

- SUMMARY.md
```
On branch link_new_page_my_schedule
```
> my_schedule page now linked

- dashboard/all_events.md
- dashboard/my_schedule.md
I forgot to do the git add . at the beginning of this PR - my fault of course. This may end up getting redone completely if the changes don't take - moved the student-only view from All Events into My Schedule where it belongs.
> move student view to correct my schedule page

- dashboard/my_schedule.md
```
On branch event_context_buttons_admin_view
```
> added initial text info about context buttons

- dashboard/my_schedule.md
```
On branch move_admin_stuff_up_context_buttons
```
> rearranged page a bit and slight edit

- dashboard/my_schedule.md
```
On branch promote_headers
```
> trying to get lower chapters to appear - test

- dashboard/all_events.md
- dashboard/calendar-search-and-filter-options.md
- dashboard/my_schedule.md
```   
On branch fix_up_all_events_page
modified:   dashboard/all_events.md
```
> cleanup in aisle three - admin - all events

- dashboard/calendar-search-and-filter-options.md
```
On branch one_more_tweak_duration_options_calendar_view
modified:   dashboard/calendar-view-options.md
```
> search and filter page needs refresh

- dashboard/calendar-search-and-filter-options.md
```
On branch small_tweak_to_test_page_refresh_remove_intro
```
> moved intro down in case causing issues

- dashboard/calendar-search-and-filter-options.md
- dashboard/my_schedule.md
```
On branch move_my_schedule_stuff
```
> moved my schedule existing stuff to my_schedule.md

- dashboard/my_schedule.md
```
On branch get_rid_of_duplicate_my_schedule_header
```
> added link to context buttons and cleaned up a bit

- learner-groups/learner-group-defaults.md
```
On branch fix_text_of_learner_group_accommodations
modified:   learner-groups/learner-group-defaults.md
```
> added reference to calendar feed in lg defaults

- programs/program-year-objective-map-visualization.md
Closes #40 as well - just a a cpl minor changes to help close this issue - program year objective visualization is well covered in the guide.
> minor capitalization caption changes prog year viz

- SUMMARY.md
```
On branch rename_help_to_help_link
```
> renamed chapter link

- courses-and-sessions/courses/README.md
```
On branch add_info_about_course_vocab
```
> added hyperlink to schools - vocab from course README

- courses-and-sessions/courses/README.md
```
On branch add_info_about_course_vocab_2
```
> added a bit more info to course README regarding vocab terms

- courses-and-sessions/courses/course-rollover.md
```
On branch add_brief_description_of_course_rollover
```
> added a bit of text - course rollover described

- courses-and-sessions/courses/course-rollover.md
```
On branch edit_course_rollover_a_bit_more
```
> added a bit of text - course rollover comment

- courses-and-sessions/courses/attach-learning-materials.md
```
On branch add_info_about_course_LM_add_existing
```
> added a bit of text about difference btw existing and new lm

- courses-and-sessions/courses/upload-new-learning-material.md
```
On branch add_search_first_spiel_to_new_course_lm
modified:   courses-and-sessions/courses/upload-new-learning-material.md
```
> slight text adjustment add new lm course

- courses-and-sessions/courses/upload-new-learning-material.md
```
On branch replace_image_course_lm_add_file_defaults
modified:   courses-and-sessions/courses/upload-new-learning-material.md
```
> minor change - waiting on image replacement

- dashboard/icons-explained.md
```
On branch update_verbiage_on_unpublished_icon
```
> minor change - unpublished update from not published

- dashboard/icons-explained.md
```
On branch update_verbiage_on_campus_record_caption
```
> minor change - campus name of record caption

- dashboard/icons-explained.md
```
On branch update_verbiage_on_campus_record_caption_one_more
```
> a few text changes more on icons_explained page

- dashboard/icons-explained.md
```
On branch one_more_text_update_labels_too_long_icons_explained
```
> a few additonal text changes on icons_explained page

- courses-and-sessions/courses/course-rollover.md
```
On branch update_description_of_course_rollover_any_course
```
> a few text changes on course rollover

- courses-and-sessions/courses/course-rollover.md
```
On branch update_description_of_course_rollover_another_quick_update
```
> a few text changes on course rollover more

- courses-and-sessions/courses/add-parent-objective.md
```
On branch update_statement_add_parent_objective_course
modified:   courses-and-sessions/courses/add-parent-objective.md
```
> a few text changes on course obj term

- courses-and-sessions/courses/edit-parent-objective.md
```
On branch update_description_before_update_parent_obj_course
modified:   courses-and-sessions/courses/edit-parent-objective.md
```
> a few text changes update parent course obj

- courses-and-sessions/offerings/edit-offering.md
```
On branch edit_offering_updates
modified:   courses-and-sessions/offerings/edit-offering.md
```
> promoted a few chapter headings for organizational purposes

- courses-and-sessions/courses/view-learning-materials.md
```
On branch update_pdf_download_vs_view_crs_and_sess
```
> quick chapter level fix - H3 >> H2

- courses-and-sessions/courses/view-learning-materials.md
```
On branch add_viewing_options_heading_chapter
```
> viewing options chapter header added

- courses-and-sessions/courses/view-learning-materials.md
```                                              
On branch fix_capitaliztion_image_caption_course_lm
```
> quick fix - standard format of image caption

- courses-and-sessions/courses/view-learning-materials.md
```
On branch capitalization_update_icons_course_lms
```
> added file disclaimer and fixed a cpl capitalizations

- courses-and-sessions/courses/view-learning-materials.md
```
On branch update_description_of_viewing_options
```
> a few more text mods

- courses-and-sessions/sessions/session-leadership.md
```
On branch update_session_lm_page_headers
modified:   courses-and-sessions/sessions/session-leadership.md
```
> added chapter headers and rearranged a bit

- learner-groups/group-assignment-tool.md
```
On branch fix_caption_lg_upload
```
* made them all match in lower case actually
> standardized image caption capitalization ... or not

- learner-groups/group-assignment-tool.md
```
On branch add_header_for_sample_file_fields_lg_upload
```
> cleaned up some text - added header

- learner-groups/group-assignment-tool.md
```
On branch update_caption_lg_sample_file
```
> slight update to header

- learner-groups/edit-group-properties/README.md
```
On branch fix_another_capitalization_edit_learner_grp
```
> slight update to header one more update

- courses-and-sessions/sessions/attach-learning-materials.md
```
On branch change_search_string_session_LM_lower_case
modified:   courses-and-sessions/sessions/attach-learning-materials.md
```
> made a few starting changes to session lm attach page

- courses-and-sessions/sessions/attach-learning-materials.md
```
On branch one_more_brief_update_lm_usage_session
modified:   courses-and-sessions/sessions/attach-learning-materials.md
```
> made a few more changes - same page

- additional-information/mesh/README.md
```
On branch update_MeSH_with_more_links_addtn_info
modified:   additional-information/mesh/README.md
```
> made a few changes - MeSH addtnl info

- courses-and-sessions/courses/edit-course.md
```                                           
On branch add_link_to_MeSH_in_crs_details
```
> made a few changes - MeSH link added to crs detail

- courses-and-sessions/courses/edit-course.md
```                                                       
On branch add_link_to_terms_in_crs_details
```
> made a few changes - vocab link added to crs detail

- courses-and-sessions/courses/README.md
```
On branch one_more_missing_MeSH_link_course_details
```
> made a few changes - added missing MeSH link to readme

- courses-and-sessions/sessions/edit-session.md
```
On branch add_bit_about_editing_URL_session_level
```
> added a bit about setting new tab ... or not

- courses-and-sessions/sessions/edit-session.md
```
On branch quick_caption_update
Your branch is up to date with 'origin/quick_caption_update'.
```
> edit session caption updates

- courses-and-sessions/courses/README.md
- courses-and-sessions/sessions/README.md
```
On branch remove_redundant_phrasing_MeSH_course
```
> a quick bit of text editing

- courses-and-sessions/courses/README.md
Fixes a sentence in course README file - added a dash for consistency with other field descriptions and for grammar accuracy
> a quick bit of text editing - punctuation update

- courses-and-sessions/courses/README.md
```
On branch update_manage_MeSH_spiel_course_README
```
> rearranged MeSH manager description - course level

- courses-and-sessions/courses/README.md
```
On branch add_link_for_competencies_from_course_README
```
> added a link to schools - competencies

- courses-and-sessions/courses/README.md
```
On branch add_link_to_manage_cohorts_course_edit
```
> added program cohorts link to course README

- courses-and-sessions/courses/README.md
```
On branch add_info_about_competencies_read_only
```
> added read-only to describe competencies course README

- courses-and-sessions/courses/README.md
```
On branch fix_CAPS_issue_in_courses_README_All_Courses
```
> fixed caps issue - ALL COURSES >> All Courses

- dashboard/language-selector.md
```
On branch update_caption_language_switcher_dashboard
modified:   dashboard/language-selector.md
```
> caption change - swtich to Spanish

- courses-and-sessions/courses/README.md
```
On branch add_title_as_course_sorting_option
```
> needed to add title as sort option

- courses-and-sessions/courses/edit-course.md
```
On branch change_vocab_terms_to_terms_for_accuracy
```
> updated caption - added link

- courses-and-sessions/courses/README.md
```
On branch add_links_to_course_README
```
> Add links to course readme

- courses-and-sessions/courses/README.md
Just an oversight from before, I needed to add a bit to the courses README.md page.
> adding terms to MeSH desc on README

- courses-and-sessions/courses/edit-course.md
```   
On branch correct_header_levels_course_actions_cohort
```
> promoted course cohorts to proper level - edit-course.md

- courses-and-sessions/courses/edit-course.md
```
On branch fix_CAPS_issue_in_courses_caption_edit_course
```
> CAPS fix and one text fix - edit-course.md

- courses-and-sessions/courses/course-summary.md
```
On branch fix_typos_and_other_text_print_summary
modified:   courses-and-sessions/courses/course-summary.md
```
> CAPS fix and one text fix - course actions print summary

- permissions.md
```
On branch add_link_to_prgram_leadership_permissions
```
> added link to program leadership - permissions.md

- permissions.md
```
On branch quick_wording_update_permissions_md
```
> quick wording adjustment - permissions.md

- permissions.md
```   
On branch add_school_leadership_link
```
> added school leadership link

- permissions.md
```
On branch add_program_year_leadership_link
```
> added program year leadership link

- courses-and-sessions/courses/README.md
```
On branch update_naming_convention_course_README
```
> one quick text edit

- courses-and-sessions/courses/README.md
```   
On branch remove_asterisks_and_add_description_course_sort_options
```
> removed unneeded asterisks and added description

- courses-and-sessions/courses/sort-learning-materials.md
```    
On branch update_learning_materials_sort_desc
modified:   courses-and-sessions/courses/sort-learning-materials.md
```
> clarified a statement about sort order - learning materials

- courses-and-sessions/README.md
```
On branch update_statement_about_courses_and_sessions
modified:   courses-and-sessions/README.md
```
> spiel updated - two steps

- courses-and-sessions/courses/README.md
quick text fix - related to #1016
> amended text from previous PR

- admin/README.md
```
On branch fix_captions_admin_console
modified:   admin/README.md
```
> fixed up admin README a bit - headers and text

- admin/README.md
```  
On branch fix_captions_admin_console_a_bit_more
modified:   admin/README.md
```
> fixed up admin README - a few more tweaks

- courses-and-sessions/courses/create-new-course.md
```
On branch update_course_new_course_page_third_image
modified:   courses-and-sessions/courses/create-new-course.md
```
> third screen shot updated

- courses-and-sessions/courses/create-new-course.md
```
On branch update_course_new_course_page_update_new_course_desc
modified:   courses-and-sessions/courses/create-new-course.md
```
> new course description spiel updated

- courses-and-sessions/sessions/edit-session-objective.md
```
On branch update_links_to_add_vocab_to_obj_session
```
> updated links and caption session objective edit

- courses-and-sessions/courses/edit-objective.md
```
On branch fix_spiel_on_course_obj_edit
```
> trimmed some unneeded text course obj edit

- courses-and-sessions/courses/edit-objective.md
```
On branch rearrange_page_edit_course_obj
```
Page rearranged to follow the logical usage flow.
> moved things around for better page flow

- dashboard/README.md
```
On branch update_spiel_dashboard_one_more
```
> updated spiel in dashboard README one more update

- README.md
```
On branch work_on_introduction_part_one
```
> introduction needs work - setting some header values here - levels

- README.md
```
On branch work_on_introduction_part_two
```
> introduction needs work - setting some header levels again

- README.md
```
On branch update_on_optimal_viewing
```
> introduction needs work - updated optimal view

- README.md
```
On branch update_on_save_events
```
This PR hopefully helps to clear up some of verbiage in the introduction regarding saving your work.
> introduction needs work - save event clarification

- README.md
```
On branch add_info_about_aborting_search
```
> Add info about aborting search

- dashboard/README.md
```
On branch change_small_to_smaller
```
> dashboard updates - small to smaller caption correction

- dashboard/README.md
```
On branch one_more_smaller_caption_update_down_page
```
This PR fixes a reference to the section updated in #1055 - needed to standardize the language.
> dashboard updates - small to smaller caption one more fix

- dashboard/README.md
```
On branch update_mobile_device_caption_to_match_link
```
> dashboard updates - caption matches link

- dashboard/materials-view.md
```
On branch update_check_box_desription_lm
modified:   dashboard/materials-view.md
```
> added bit about how course level no chk boxes

- dashboard/icons-explained.md
```
On branch add_more_info_on_location_of_icons
```
> added bit about mouse over on icons - where to see

- dashboard/icons-explained.md
```
On branch update_virtual_link_spiel
```
> more work on icons explained

- dashboard/icons-explained.md
```
On branch update_virtual_link_spiel_again
```
> more work on icons explained - header updated

- dashboard/icons-explained.md
```
On branch update_description_of_att_req_image
```
> more work on icons explained - fixed location desc of att req

- courses-and-sessions/courses/edit-course.md
```
On branch add_pre_filter_description
```
> edit course - pre-filter explained

- courses-and-sessions/sessions/edit-session-objective.md
```
On branch fix_capitalization_of_edit_course_sections
```
> actually edit session not course but still fixing

- courses-and-sessions/courses/course-rollover.md
- courses-and-sessions/sessions/edit-session-objective.md
```
On branch update_rollover_to_previous_year_desc
```
> added a bit of explanation to rollover prev yr

- dashboard/search.md
```
On branch min_text_string_for_global_search
```
Added a bit more about the `"keep typing..."` message and why and when it appears in global search.
> added a bit of explanation about minimum global srch string

- README.md
```
On branch add_esc_description
```
> added a bit of explanation about using esc to escape

- dashboard/search.md
```
On branch cancel_global_search
```
> added bit about global search cancel search

- courses-and-sessions/courses/edit-course.md
```
On branch add_link_for_sort_course_obj
```
> added link to sort objectives course level

- courses-and-sessions/sessions/README.md
```
On branch outdent_session_list_settings
```
> better header levels setting sessions README

- courses-and-sessions/courses/edit-course.md
```
On branch update_compentency_desc_course_and_edit
```
> course obj edit and competency desc added

- SUMMARY.md
```
On branch new_page_for_maintain_vocab_course_level
```
> added link to vocab term course level

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch for_now_add_link_to_session_vocab_maint
```
> added link to vocab term session level

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch update_link_with_new_caption_sess_vocab_terms
```
> updated link with updated caption spelling sess vocab terms

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch update_course_vocab_terms_page
```
> updated intro spiel vocab terms page course level

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch update_header_sizes_course_vocab
```
> promoted some headers - looking for chapters - course vocab

- courses-and-sessions/courses/edit-course.md
- schools/vocabularies.md
```
On branch update_terms_link
modified:   schools/vocabularies.md
```
This also fixes a few capitalization issues - in vocabuularies.md >> school level.
> fixed a link to the new vocab terms course page

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch add_term_added_image_and_spiel_saved
```
> chapter heading update course terms

- courses-and-sessions/courses/vocabulary_terms.md
```
On branch update_search_and_find_term
```
Formatting one of the "H2" headers to match better with some of the other ones.
> course vocab chapter title update

- courses-and-sessions/courses/README.md
```
On branch add_link_to_school_vocab_setup
```
> added school link as well for course terms

- courses-and-sessions/courses/course-rollover.md
```
On branch update_course_rollover_spiel
```
> added a new detail on course rollover

- README.md
```
On branch new_image_user_guide_search_links
```
> text updated first - keyboard command to follow links

- SUMMARY.md
```
On branch update_reports_curriculum_reports_1
new file:   reports/curriculum_reports.md
new file:   reports/subject_reports.md
```
> new chapters added - reports

- reports/reports.md
```
On branch update_reports_curriculum_reports_2
```
> capitalization update on captions - force prev changes too

- reports/curriculum_reports.md
This PR promotes each chapter section by one level. This sets up further forthcoming improvements in this documentation. The navigation in the guide hopefully will be improved by this PR.
> chapter improvements hopefully - promoted by one level

- reports/curriculum_reports.md
related to #1127 ...
```
On branch fix_typo_from_previous_PR
modified:   reports/curriculum_reports.md
```
Typo in #1127 fixed in this PR - chapter sections now set hopefully.
> chapter improvements hopefully - fixed typo from prev PR

- reports/curriculum_reports.md
This PR adds a spiel about using the "Select All or None" check box - two click are required if some courses have been selected.
> added bit about using select all or none checkbox

- SUMMARY.md
```                                       
On branch add_competencies_link_course_to_page
```
> competencies.md added to summary.md - missed somehow

- courses-and-sessions/courses/competencies.md
```
On branch update_competency_course_level_text
```
> competencies.md school update

- courses-and-sessions/courses/competencies.md
```
On branch update_competency_course_level_text_mapping
```
> competencies.md school update - one more update

- courses-and-sessions/README.md
```
On branch first_effort_sorting_session_links
modified:   courses-and-sessions/README.md
```
> updated sort order a bit courses-and-sessions/README.md

- programs/add-program-year.md
```
On branch add_bit_about_avail_program_years
```
> added brief spiel about program year creation

- README.md
```
On branch try_red_just_to_see_if_it_works
```
> this is a test - trying some color formatting red this time

- reports/subject_reports.md
```
On branch two_links_on_report_output
modified:   reports/subject_reports.md
```
> adding more info on output links - subject reports

- courses-and-sessions/courses/visualizations.md
```
On branch update_visualizations_starting_image
```
> moved spiel about objective viz to correct section

- courses-and-sessions/courses/visualizations.md
```
On branch update_visualizations_starting_image
```
> data table sub-chapters need to be more prominent

- courses-and-sessions/courses/visualizations.md
```
On branch update_visualizations_remove_as_shown
```
> cpl quick text updates - setting stage for data download section

- courses-and-sessions/courses/visualizations.md
```
On branch update_objectives_viz_description
```
> clarified hopefully about the meaning of course obj viz mapping

- courses-and-sessions/courses/visualizations.md
```
On branch fix_casing_sort_order_one
```
> fixed hopefully a few file name and text casing issues

- courses-and-sessions/courses/visualizations.md
```
On branch add_fields_of_output
```
> added detail of fields outputted in data table

- courses-and-sessions/courses/visualizations.md
```
On branch update_visualization_spiel_vocab
```
> fixed typo in visualizations.md

- courses-and-sessions/courses/visualizations.md
```                                        
On branch update_spiel_on_visualizations
```
> added a bit of information to introductory spiel

- courses-and-sessions/courses/visualizations.md
```
On branch update_description_of_instructor_hi_lvl_viz
```
> updated explanation of high level instructor viz chart

- courses-and-sessions/offerings/create-single-offering.md
```
On branch fix_description_of_permissions_note
modified:   courses-and-sessions/offerings/create-single-offering.md
```
> updated explanation of permissions note - single offerings

- courses-and-sessions/offerings/create-small-group-offerings.md
- courses-and-sessions/offerings/teaching-reminders.md
```
On branch fix_broken_link_small_group_make_recurring
modified:   courses-and-sessions/offerings/teaching-reminders.md
```
> bad link - hopefully fixed with this PR

- courses-and-sessions/offerings/create-small-group-offerings.md
```
On branch sub_groups_mentioned
```
> cpl quick text mods

- courses-and-sessions/offerings/create-small-group-offerings.md
```
On branch offering_editor_top_part_update_text_update
```
Standardized capitalization on this page regarding start and end dates and times,
> added a few text updates

- courses-and-sessions/offerings/create-small-group-offerings.md
```
On branch update_text_about_small_groups_vs_indiv_offering
```
> added a few more text updates

- courses-and-sessions/sessions/session_actions.md
```
On branch update_session_actions_desc
modified:   courses-and-sessions/sessions/session_actions.md
```
> slight update to session actions

- dashboard/search.md
```
On branch add_bit_about_lm_contents_in_global_search
```
> text updates - added lm content to search region

- dashboard/search.md
```
On branch add_bit_about_lm_contents_in_global_search_text_add
```
I lifted some text from @saschaben's recent Ilios update. It may end up being a bit too much text for this guide in the long term; but I wanted to get it in there. Could be edited later.
> text updates - added lm content global search spiel

- courses-and-sessions/sessions/session-leadership.md
```
On branch update_session_leadership_text
modified:   courses-and-sessions/sessions/session-leadership.md
```
Cleaned up the chapters / sections a bit and updated names from being redundant.
> updated text a bit - session leadership

- learner-groups/edit-group-properties/README.md
- learner-groups/edit-group-properties/edit-group-membership.md
```
On branch fix_capitalization_of_filter_by_group_title
modified:   learner-groups/edit-group-properties/edit-group-membership.md
```
> a cpl quick text fixes in learner group edit members

- learner-groups/remove-learner-group.md
```
On branch fix_unneeded_capitalization
modified:   learner-groups/remove-learner-group.md
```
> made the remove-learner-group page more consistent

- dashboard/calendar-feed-options.md
```
On branch put_link_to_lti_repository_in_guide
modified:   dashboard/calendar-feed-options.md
```
> started updating LTI stuff

- SUMMARY.md
```
On branch update_summary_md_with_new_LTI_dashboard_link
```
> started updating LTI stuff - summary.md link added

- dashboard/LTI_integration.md
- dashboard/calendar-feed-options.md
```
On branch put_current_content_LTI_into_new_page
modified:   dashboard/LTI_integration.md
modified:   dashboard/calendar-feed-options.md
```
No big modifications done ... yet. Moved current content into a new chapter where it should have always been.
> started updating LTI stuff - current content moved

- dashboard/LTI_integration.md
Added a little bit more to the description of the LTI dashboard and how we can be of service.
> a quick phrasing follow up on LTI

- programs/add-program-year.md
```
On branch update_rolled_over_prog_year_properties
```
> spiel added indicating rolled over attributes

- programs/add-program-year.md
```
On branch bullet_points_need_to_be_bold_prog_year_rollover
```
> bullets fixed bold - more description added

- SUMMARY.md
- programs/edit_program_year.md
```
On branch new_page_edit_program_year
new file:   programs/edit_program_year.md
```
As title indicates, a new page was added `edit_program_year.md` - `SUMMARY.md` was modified to display this new page - content is pending - mostly will be pasted in for now and then later modified.
> working on program year - new page added

- SUMMARY.md
- programs/objectives_maintenance.md
```
On branch new_page_maintain_program_year_objectives
new file:   programs/objectives_maintenance.md
```
> added page to move content into

- programs/add-program-year.md
```
On branch fix_program_year_attributes_list
```
> rearranged add_program_year a bit

- programs/edit_program_year.md
```
On branch add_section_for_program_year_objectives_link
modified:   programs/edit_program_year.md
```
> added a link for continuity sake to prog year objective

- admin/add-learners-to-cohort.md
```
On branch admin_console_chapter_setup_and_bulk_upload_update
modified:   admin/add-learners-to-cohort.md
```
> learners or non-learners can be uploaded in bulk

- admin/add-learners-to-cohort.md
```
On branch add_important_note_about_bulk_user_upload
modified:   admin/add-learners-to-cohort.md
```
> important note added about bulk user upload button

- admin/add-learners-to-cohort.md
This PR is basically a small text update to the previous commit #1282.
> important note added about bulk user upload button update

- admin/add-learners-to-cohort.md
typo from #1284 fixed here - end of sentence needs a period. not a comma,
> new images and text student upload options fix

- schools/README.md
```
On branch institutional_information_not_CI_part_one
modified:   schools/README.md
```
> fixed link but not destination ... yet

- SUMMARY.md
```
On branch institutional_information_not_CI_part_two
```
> fixed chapter link in summary

- schools/curriculum-inventory-institution-information.md
```
On branch institutional_information_not_CI_part_three
modified:   schools/curriculum-inventory-institution-information.md
```
> started work on instituion-information page

- SUMMARY.md
- schools/manage_emails
```
On branch new_section_manage_emails
new file:   schools/manage_emails
```
> new page created for managing email addresses

- schools/manage_emails.md
```
On branch fix_content_manage_emails_admin
modified:   schools/manage_emails.md
```
> spiel update - one only admin email acct

- courses-and-sessions/offerings/create-small-group-offerings.md
```
On branch one_offering_per_group
```
> comment added - parent group de-select

- dashboard/LTI_integration.md
```
On branch add_link_to_hosting
modified:   dashboard/LTI_integration.md
```
This PR adds a link to our hosting informational page on iliosproject.org and creates a cpl chapter headers on the above-mentioned page.
> text and link added for hosting

- reports/reports.md
- reports/subject_reports.md
```
On branch move_intro_spiel_to_main_reports_page
modified:   reports/subject_reports.md
```
> text modified - moved stuff around for better placement

- reports/subject_reports.md
```
On branch add_copy_report_to_subject_reports
modified:   reports/subject_reports.md
```
This PR also promotes some of the headers to higher levels to make reading it all easier.
> text modified - added section for copy subject report

- dashboard/my-profile.md
```
On branch increase_size_date_picker_token
modified:   dashboard/my-profile.md
```
> added a bit more about date picker for token expiration

- dashboard/my-profile.md
```
On branch fix_casing_of_image_captions_token
modified:   dashboard/my-profile.md
```
> fixed casing and name matching of image files

- learner-groups/new-learner-group.md
```
On branch initial_group_membership_update
modified:   learner-groups/new-learner-group.md
```
> changed a phrase to indicate initial membership

- courses-and-sessions/sessions/README.md
```
On branch viewing_options_session_list_update
```
> updated chapter heading

- dashboard/home.md
```
On branch replace_WaaG_dashboard_initial_image
modified:   dashboard/home.md
```
Image not actually replaced ... yet. But a bunch of setup changes and text changes were done now in preparation for this to occur.
> new section added - student view WaaG

- dashboard/search.md
Description updated here. 
```
On branch output_filters_rename_global_search
```
> updated description - output filters - global search

- dashboard/search.md
```
On branch remove_three_char_message_global_search
```
This is related to https://github.com/ilios/ilios/issues/6440 since the three char minimum and / or messaging upon text entry into search field may need to be fixed. For now, removed this content from the guide.
> begrudgingly removed some content global search

- dashboard/search.md
```
On branch add_a_bit_back_to_global_search
```
> added a bit more back to help with previous removal

- dashboard/search.md
```
On branch remove_one_more_bit_about_suggested_values_global_srch
```
> had to remove a bit about suggested values to follow

- dashboard/home.md
```
On branch quick_typo_fix_WaaG_admin_view
modified:   dashboard/home.md
```
> typo fix and additonal text added

- dashboard/search.md
```
On branch add_bit_about_how_filters_are_applied_global_srch
```
> added a bit more about the defaults being applied

- dashboard/calendar-view-options.md
```
On branch update_description_of_cal_start_time
modified:   dashboard/calendar-view-options.md
```
> calendar start time description update one

- dashboard/calendar-view-options.md
```
On branch fix_verb_tense_error_since_image_appears
modified:   dashboard/calendar-view-options.md
```
> corrected text entry for image

- courses-and-sessions/offerings/multi-day-offerings.md
```
On branch update_image_caption_multi_day
modified:   courses-and-sessions/offerings/multi-day-offerings.md
```
> caption fix to more closely match file name

- dashboard/search.md
```
On branch update_show_more_description_global_search
```
> fixed a typo and clarified a bit

- dashboard/search.md
```
On branch add_bit_about_return_key_global_search_re_run
```
> added a bit more about running global search additional times

- courses-and-sessions/sessions/README.md
```
On branch fix_session_list_caption
```
> fixed a cpl of captions for more uniform formatting

- courses-and-sessions/sessions/README.md
- courses-and-sessions/sessions/add-new-session.md
```
On branch add_sections_for_top_and_bottom_session_detail
```
> new image and section upper and lower

- glossary.md
```
On branch add_intstructional_notes_to_glossary
```
> added a spiel for instructional notes locations

- courses-and-sessions/sessions/attach-learning-materials.md
```
On branch fix_instructional_notes_session_level_captions
modified:   courses-and-sessions/sessions/attach-learning-materials.md
```
> edited a caption and added a spiel

- dashboard/search.md
This PR starts the process of adding images for "show less" functionality in Global Search. 
An upcoming PR will also add images showing the results of clicking "show more". For now, this sets up the stage for all of that -- coming soon.
> section added - more images needed show more and show less

- dashboard/search.md
```
On branch add_show_less_to_global_search_area_text_update
```
> a bit more text added to explain when show less appears

- SUMMARY.md
```
On branch add_program_cohorts_page_to_summary
```
> attempting to add to summary.md but messed up branch checkout

- additional-information/mesh/README.md
```
On branch add_link_to_session_MeSH_addtnl_info
modified:   additional-information/mesh/README.md
```
> added a cpl links - to session and course MeSH

- courses-and-sessions/sessions/independent-learning-module-ilm.md
```
On branch promote_a_few_sections_session_ILM
modified:   courses-and-sessions/sessions/independent-learning-module-ilm.md
```
> caption and header updates

- courses-and-sessions/sessions/add-new-session.md
```
On branch brief_update_ILM_intro
```
> updated the intro on add new session regarding ILM's

- courses-and-sessions/sessions/edit-session.md
```
On branch fix_a_cpl_links_in_edit_session
```
> fixed a cpl broken links caused by moving stuff around

- courses-and-sessions/sessions/edit-session.md
```
On branch fix_some_image_captions
```
> moved and modified a few links for better flow sess edit

- courses-and-sessions/publishing.md
```
On branch update_publishigng_page_req_vs_optional_fields
modified:   courses-and-sessions/publishing.md
```
> new sections for required vs optional fields publishing

- dashboard/materials-view.md
```
On branch update_list_of_three_avail_states_LM
modified:   dashboard/materials-view.md
```
> added a bit more detail on three states avail

- dashboard/icons-explained.md
```
On branch change_pre_work_to_prerequisites
```
> using prerequisites instead of pre-work on icons explained page

- courses-and-sessions/courses/edit-course.md
```
On branch add_bit_about_rollover_icon_missing_locked_course
```
> added comment about locked course no rollover

- courses-and-sessions/courses/course-summary.md
```
On branch update_spiel_about_print_summary_usage
modified:   courses-and-sessions/courses/course-summary.md
```
> added comment searching downloaded print summary

- schools/add-new-school.md
```
On branch fix_new_school_closing_spiel
modified:   schools/add-new-school.md
```
> made a few text fixes - add new school

- programs/edit_program_year.md
```
On branch add_bit_about_locking_program_year
modified:   programs/edit_program_year.md
```
> added spiel about locking and deleting prog year

- programs/edit_program_year.md
```
On branch explain_default_unlocked_prog_year
modified:   programs/edit_program_year.md
```
> added spiel about default being unlocked

- dashboard/calendar-search-and-filter-options.md
```
On branch update_caption_to_match_link_duration_options
```
> made sure links matches destination

- courses-and-sessions/courses/course-leadership.md
```
On branch change_caption_remove_director
```
> slight text change hopefully for more clarification
