ilios/user-guide

additional-information/mesh/add-mesh-to-course-objective.md

This simply fixes a typo where objectives were associated with Program rather than Program Year. Program Year is correct.

add prog year MeSH - fix typo

---

dashboard/README.md

The Language Selector link had a bunch of unnecessary asterisks after it.

Update README.md - asterisk extras rmvd

---

learner-groups/remove-learner-group.md

Only when Learner Groups are unattached to offerings can they be deleted. This is a change from the lack of membership which was the deletion criteria previously.

updating the text of LG deletion

---

courses-and-sessions/offerings/edit-offering.md

updated the screen shot and added some relevant text - starting the process of documenting the Shift click technique for selecting or de-selecting nested learner groups

replace the LG selector screen shot

---

dashboard/README.md

Using the "images" folder and an updated image instead of .gitbook/assets - file replaced - markdown updated

Replaced Ilios Flyout Image

---

dashboard/README.md

Some asterisks were added to the end of the Search (Global Search) url - not needed - removed.

removed a few bogus chars

---

dashboard/README.md

This was in the Dashboard section - just as an FYI. Removing the link to MyReports.

remove link to MyReports

---

dashboard/icons-explained.md

I accidentally left a cpl of these `.images/` rather than `images` in there so images were not appearing when they should have -- fixed this with this PR.

icons_explained_links_fixed

---

SUMMARY.md

fixes #150 - this removes the reference to `my_courses` from the table of contents contained in the file `SUMMARY.md` - also closes the associated issue - *NOTE* - the files remain in the `user_guide` repo but are no longer displayed anywhere - eventually will clean up

removed_my_courses_from_TOC

---

courses-and-sessions/courses/README.md

I noticed there were a bunch of asterisks in front or a link to "Courses" on the README.md in the Courses chapter - hopefully this will fix that issue.

fixed_course_level_link

---

courses-and-sessions/courses/course-rollover.md

removed a reference to not being able to roll a course back in time - this is possible - a bit of formatting fix - some unneeded asterisks ** - page modified `course-rollover.md`

made a few text changes in course-rollover.md

---

courses-and-sessions/offerings/teaching-reminders.md

After a full rebase and a botched pull request, this is just a couple of simple text changes and confirmation of the location and name of the correctly linked file in `courses-and-sessions/offerings/teaching-reminders.md` - new image location `images/teaching_reminders`.

final update - teaching-reminders.md

---

dashboard/calendar-view.md

I am not sure what is going on with the following image - `(../images/unpubiished_icon.png)`.
It is supposed to show the unpublished pencil icon. It's a small image it's true but it was not showing up at all. I am not sure this will fix that issue but it is an initial effort. After that, I may choose to recapture the image. 
Page affected by this PR `https://iliosproject.gitbook.io/ilios-user-guide/dashboard/calendar-view`

attempted to updated unpublished icon

---

dashboard/calendar-view.md

This time I put the offending image (or lack thereof) in a the following type of markup ...
```  
<figcaption>
<p>Unpublished</p>
</figcaption>
</figure>
```
Hopefully at least the little image should show up - if not, @jrjohnson may get a ping from me down the road.
page affected by this change -- `dashboard/calendar-view.md`

attempted to update unpublished icon 2nd try

---

dashboard/calendar-view.md

This is sort of a test PR to see if either approach leads to the revealing and display of the `unpublished_icon.png` image file - a small one to be sure - to appear. Whichever method (full HTML) or traditional image link in markdown works will be the victor. If neither works, I will figure out how to replace the image and see what happens next.

attempted to updated unpublished icon 3rd try

---

dashboard/calendar-view.md

I think this may do it. I'm not using the HTML block, which wasn't displaying the image correctly either. However, redoing and relinking the original seemed to do the trick - this PR gets rid of the HTML block and refreshed the original image link which now seems to appear correctly.
`dashboard/calendar-view.md` is the page affected by this -- image file is `../images/unpubiished_icon.png`

attempted to updated unpublished icon final try

---

dashboard/calendar-view-options.md

* file affected by this PR - `dashboard/calendar-view-options`
* added image descriptions to images that were lacking them - helpful for debugging
* files already properly named and in correct folder `../images/calendar_view_images`

calendar_view_options - added remaining image descriptions

---

curriculum-inventory/README.md

I added an introductory spiel to the now much harder to find "Curriculum Inventory" page in the user guide.
This covers the expiration of the CI Upload functionality which is no longer supported by the AAMC.
* user guide page affected by this PR ... `curriculum-inventory/README.md`

added modifed spiel from AAMC about curriculum inventory

---

glossary.md

* user guide markdown page affected by this PR ... `glossary.md`
* cleaned up markdown a bit 
* added brief description for program year

Add program year to glossary

---

courses-and-sessions/courses/README.md

* user guide markdown page involved with this PR ... `courses/README.md`
* added brief (slightly shorter than glossary version) description of "Vocabularies" to the course level README - to give more context to the concept of "Terms"

added vocabularies desc to course README

---

courses-and-sessions/courses/README.md

This is related to #325 except I realized Vocabularies themselves are not really course attributes at that level. this PR updates and makes that distinction a bit more clear.

updated vocabularies desc to course README

---

dashboard/README.md

* user guide markdown page involved with this PR ... `dashboard/README.md`
I noticed some strange brackets remaining around `Curriculum Inventory` on the main Dashboard page. All of the other links have these brackets as well but since they are links, do not appear in the output. This PR will hopefully sort that out.

removed brackets from CI Dashboard link

---

older_files/my-courses.md
older_files/reports.md

* markdown user guide files affected by this PR ... `my-courses.md` and `reports.md`
* these have been moved in previous PR to the following location ... `older_files` - why? because they are no longer in use
* links fixed up on these removed pages just to get the images out of gitbook and to notate where the files have been moved to ...

updating my-courses.md and reports.md with new image locations

---

learner-groups/README.md

Sometime I have been putting too many asterisks in certain locations trying to a link to be bold. This is a PR to fix a couple of badly formatted ones I noticed ...
* page updated by this PR ... `learner-groups/README.md`

fix a few badly formatted links

---

programs/add-program-year.md

why did this not show up on the repo?
`programs/add-program-year.md` was modified - plural reduced to singular for accuracy

quick typo fix

---

courses-and-sessions/sessions/edit-session.md

* page affected by / involved with this PR ... `courses-and-sessions/sessions/edit-session.md`
I needed to remove the part about a difference between Instructional Notes and Session Description which does not exist. Removed the untrue content.

more info on session level instructional notes

---

dashboard/README.md

This corrects the assertion that there are 4 options available on WaaG Dashboard - that is no longer true - there are only 3 options.

updated option count on dashboard

---

courses-and-sessions/offerings/README.md

I noticed a typo on this page and fixed it.

fixed typo in courses-and-sessions/offerings/README.md

---

dashboard/README.md

* page involved in this PR ... `dashboard/README.md`
* updates description of `Courses and Sessions` to include the fact that it is not just a filterable list but actually the location to modify courses and sessions.

updated courses and sess link in dashboard page

---

dashboard/event-detail-view.md

related to #361 - new image added had a name I wanted to fix to match the rest of the naming conventions used for the image files so `ILM_Detail` is now `ILM_detail`

event detail update - fixed title case of image file

---

courses-and-sessions/offerings/create-small-group-offerings.md

* page affected by this PR ... `courses-and-sessions/offerings/created-small-group-offerings.md`
* the link to `https://iliosproject.gitbook.io/ilios-user-guide/courses-and-sessions/offerings/recurring-event` was messed up - poorly formatted - this is an attempt to fix that

attempt at fixing make recurring link formatting

---

dashboard/event-detail-view.md

I checked on other pages - it seems the `###` size helps to create an "on this page" link which is what I am hoping for - learning material activity check boxes on `dashboard/event-detail-view.md`.

changed size hoping to get an on this page link

---

dashboard/my-profile.md

I wanted the `Other Fields` area to be an option in the "on this page" section - converted it to `###` rather than `$$[string]$$` - hopefully this will work.
```
modified:   dashboard/my-profile.md
```

made other fields into larger chapter

---

courses-and-sessions/sessions/independent-learning-module-ilm.md

```
modified:   courses-and-sessions/sessions/independent-learning-module-ilm.md
```
I notice some preceding asterisks which need to be removed. Hopefully this PR will do this. I will be testing this later as well as I am redoing the `Course and Sessions` chapters.

trying to get rid of bad asterisks in ILM section

---

courses-and-sessions/courses/edit-course.md

```
```
There was a busted link on the page listed above - this PR is an effort to fix that.

configuring a busted link to course details

---

courses-and-sessions/courses/edit-course.md

`modified:   courses-and-sessions/courses/edit-course.md`
The above page was modified - I tried to make it flow better with some BOLD headers now becoming H3's or ### in markdown. A couple of ###'s were promoted to ## or H2 as the case may be. On this page navigation has been improved here. The images will be next to be replaced - next phase of this page.

promoted some headers for better guidance on page

---

courses-and-sessions/courses/edit-course.md

`modified:   courses-and-sessions/courses/edit-course.md`
The "Remove Cohort" header needed to be increased in size to H3 or in markdown ###. This helps with indentation and navigation of the page.

remove cohort header enlarged for clarity

---

courses-and-sessions/courses/add-parent-objective.md

`modified:   courses-and-sessions/courses/add-parent-objective.md`
Weird one - I had made this same change but on a branch that I may have deleted from GitHub. I did not delete my local branch I don't think. Anyway, I created a new branch - the one I am using now. I never saw the PR on GitHub and my changes were not reflected in the local master branch so fixing that up now. This was a small change on a label caption - a necessary change.

updated image caption select course

---

courses-and-sessions/courses/edit-parent-objective.md

`modified:   courses-and-sessions/courses/edit-parent-objective.md`
A mis-spelled word and header needs to be fixed. That is happening here.

quick markdown typo fix

---

courses-and-sessions/courses/sort-objectives.md

`modified:   courses-and-sessions/courses/sort-objectives.md`
There is a way to add an "introduction" to any chapter / page in the user guide - it looks like and is helpful to the user - will use this same technique in many or most chapters.

added an introduction to the chapter - reuse elsewhere

---

additional-information/mesh/add-mesh-to-course-objective.md

```
On branch re-link_MeSH_to_crs_obj_images
modified:   additional-information/mesh/add-mesh-to-course-objective.md
```
moved images which need to be updated to new location in #452 and linked them correctly with this one

re-linked images to new location

---

courses-and-sessions/courses/course-rollover.md

```
On branch fix_up_course_rollover_typo_and_markdown_fix
```
This should finish up at least the "Future" rollover of a course section. "Current" and "Past" may need some updates still.

a cpl of fixes - future course rollover only

---

courses-and-sessions/courses/course-rollover.md

```
On branch fix_up_course_rollover_current_year_starting_pt
```
This is just a quick one to remind myself to fix up current year course rollover with new screen shots soon. Fixed a cpl of capitalization errors here - I'm leaning towards fewer unnecessary "proper" nouns when they are not indeed proper.

a cpl of fixes - current year rollover only

---

courses-and-sessions/courses/attach-learning-materials.md

```
On branch one_more_fixup_attach_course_LM
```
Still trying to sort out how the "introductions" work and whether an H1 # is needed at the top of the page to get the introduction to appear. It seems redundant since the H1 gets displayed based on what is entered in the `summary.md` file which is basically the outline of the whole thing.

adding an intro to attach course learning materials 2nd try

---

courses-and-sessions/courses/attach-learning-materials.md

```
On branch fix_up_attach_course_LM_intro
```
I was not aware of this until now but there is a maximum length of any given page's "introduction" section. This PR trims the introduction section of the above referenced page to fit.

trimmed intro to attach course LM - there is a max

---

courses-and-sessions/sessions/add-new-session.md

```
On branch fix_up_add_new_session_chapters
```
* deleted some text that no longer had the correct associated images and was repeated elsewhere
* added links to point user to correct location for the above

cleaned up markdown add new session

---

courses-and-sessions/publishing.md

```
On branch fix_publishing_page_missing_images
modified:   courses-and-sessions/publishing.md
```
The images are all there so the branch is not actually named correctly. The images are a bit outdated this is true. I may replace them. This PR fixes some heading and navigation-related issues.

fixed up a few headers - no missing images bad branch name

---

courses-and-sessions/courses/course-leadership.md

```
On branch promote_student_advisor_to_header
```
In order to make this a bit more prominent, at least at Course level, I made the "Student Advisor" label into H2 or in markdown "##".

made student advisor label into header

---

courses-and-sessions/courses/course-leadership.md

```
On branch fix_student_advisor_header_to_H3_not_H2
```
Initially from the previous PR #488, the header was promoted too much. This fixes that and puts in a better position on the page.

updated student advisor label header size - a bit smaller

---

README.md

```
On branch fix_introduction_to_guide
```
I noticed the previous intro sentence was too long to fit into the allotted space. It may require a second round of truncation but let's try this for now.

shortening intro spiel to fit into alloted space

---

instructor-groups/README.md

```
On branch update_instructor_group_description
modified:   instructor-groups/README.md
```
A bit was added here to include details on how instructor groups do not need to be rolled over or re-created and how they exist in perpetuity.

updated instructor group description

---

courses-and-sessions/offerings/create-single-offering.md

```
On branch add_link_to_offerings_editor_calendar
modified:   courses-and-sessions/offerings/create-single-offering.md
```
Added information about the positioning of the offerings editor calendar on the page.

added link to offering editor calendar - navigation

---

courses-and-sessions/courses/add-parent-objective.md

```
On branch get_rid_of_numbers_in_chapters_add_parent_to_crs_obj
modified:   courses-and-sessions/courses/add-parent-objective.md
```
In the rest of the guide, unless specifically pointed out in a diagram, there is no usage of numerical chapters / sections. They don't need to be numbered unless there is a reason for the numbering scheme. This removes the numbering scheme from the `courses-and-sessions/courses/add-parent-objective.md` page.

got rid of chap / section numbers on page

---

schools/vocabularies.md

```
On branch fix_typo_in_schools_vocabularies
modified:   schools/vocabularies.md
```

poorly placed asterisks on this page - fixed to match pattern

---

SUMMARY.md

``` modified:   SUMMARY.md```
Updated the chapter for Schools >> "School Leadership" to be simply "Leadership". The remaining aspect of this chapter - images and text - will be updated later this week. This reflects recent naming convention updates in the interface.

chapter name change - school leadership >> leadership

---

courses-and-sessions/courses/course-summary.md

```
On branch fix_image_link_course_summary_top
modified:   courses-and-sessions/courses/course-summary.md
```
I screwed up and forgot to fix the link in the related PR #560 - I replaced the image but forgot to fix the page that links to it. This PR fixes that issue.

link fixed - print summary

---

SUMMARY.md

```* [Program Year Objective Visualization](programs/program-year-objective-map-visualization.md)```
The line above used to be in the `SUMMARY.md` file. The page is still there but hidden in case we bring it back.
```
On branch hide_program_year_objective_viz_page
```

removed link to py obj vizualization

---

programs/add-program-year.md

This PR is an attempt to explain why the activation / de-activation toggles for PY objectives are not usable in expanded mode.

toggle not light bulb - description added

---

courses-and-sessions/courses/edit-objective.md

```
On branch add_headers_for_attach_vocab_terms_to_crs_obj
```
I realized there was a duplicated header at the top of the page - trying to better organize the headers on this page to flow better. This is hopefully just a first step in that process.

got rid of duplicated page header

---

dashboard/week-at-a-glance.md

```
On branch fix_check_box_state_numbering_WaaG
modified:   dashboard/week-at-a-glance.md
```
I have noticed recently that numbered lists especially these ones that are using HTML as well as markdown looked weird - bad vertical spacing so I got rid of the attempt at numbering - I will want to check this one to see if it is an improvement - possibly even before merging - will assign to myself.

attempt to fix numbering format WaaG page chk box states

---

courses-and-sessions/courses/create-new-course.md

```
On branch fix_double_header_create_new_course_redux
modified:   courses-and-sessions/courses/create-new-course.md
```
I am actually a bit confused about what shows up when or why. Flattened everything to H2 style headers for testing purposes. May fix this up later but for now -- this PR.

fixed course list flattened all to H2

---

courses-and-sessions/courses/course-rollover.md

```
On branch current_year_rollover_link_and_course_overview_det
```
There was a duplicate, unneeded header - hopefully this PR removes this. I am starting the process of redoing this area of the guide - the course rollover functionality exists in the Course Overview section, which will be broken out and broken down going forward.

course rollover update - rmvd dup hdr - updated desc

---

courses-and-sessions/courses/README.md

```
On branch explain_four_main_areas_of_courses_section
```
Wrong branch name since at this point only three (not four) areas are mentioned - this formatting may be quickly revised - starting point for better breakout and description on courses page.

three areas not four explained courses

---

courses-and-sessions/courses/README.md

```
On branch update_course_overview_heading_vs_details_README
```
Another commit coming soon but this one sets up a section for the "Heading" on the Course page, which actually appears above the "Overview".

added section for heading - above overview

---

courses-and-sessions/courses/README.md

```
On branch update_course_overview_heading_vs_details_README
```
made sure that the dash is directly next to the bold so it takes effect - learning how to best do this - may require yet another effort after this one

heading area course README a third attempt at dashes or bulletpt

---

courses-and-sessions/courses/README.md

```
On branch fix_uneeded_dash_courses_README
```
Reviewing the courses README.md page, I noticed there was a confusing dash that needed to be removed - this PR fixes that issue.

removed dash from courses README - needed to be removed

---

courses-and-sessions/courses/README.md

```                                         
On branch make_it_easier_to_read_in_design_mode
```
I was doing some testing as far as which vertical space adjustments would appear in the markdown output and if it even made a difference. It appears it does not make a difference so I am reverting the previous changes and going with the easiest format to read in design mode since the output is not directly affected.

tinkering with vertical space heading alignments two

---

courses-and-sessions/courses/README.md

```
On branch fix_info_overview_not_heading_course_id
```
I realized that the `course ID` field is actually in what I am describing as the Overview section - not Heading - of the Course - this PR fixes that.

fixed description - course ID overview not heading - README - courses

---

courses-and-sessions/courses/README.md

```
On branch update_session_header_indentations
```
Related to #658 in the sense I am fixing up the final section to get them all to match format-wise.

fixed indentation of session list to match other sections

---

courses-and-sessions/courses/course-leadership.md

```
On branch change_caption_to_manage_leadership_no_school
```
I actually updated the link to `Click to Manage` since this is the first step only and it is actually more accurately stated this way.

updated one more link to leadership not school leadership

---

courses-and-sessions/courses/README.md

```
On branch remove_parentheses_from_leadership_link
```
This cleans up the formatting of the previous PR #674 - can use this going forward to link to more sections.

remove parentheses from link to leadership

---

additional-information/mesh/README.md

```
On branch add_link_on_MeSH_to_new_page
modified:   additional-information/mesh/README.md
```
The new page was added in #677 and the TOC was updated in #678 - this PR adds the link onto the main MeSH page to point to the newly created file.

updated MeSH page to include link to new session MeSH obj page

---

courses-and-sessions/courses/learning_materials.md

```
On branch fix_text_in_new_course_lm_page_fix_typo
modified:   courses-and-sessions/courses/learning_materials.md
```
I think the `introduction` header types have a text maximum, which I had exceeded. This PR truncates this back down to be below the maximum text length.

fixed truncated introduction on learning_materials.md page

---

courses-and-sessions/courses/add-objective.md
courses-and-sessions/courses/course_objectives.md

```
On branch update_objectives_new_page_with_introduction
modified:   courses-and-sessions/courses/add-objective.md
```
I realized that if a parent page contains only an "introduction", the subsequent pages appear with links automatically on the main page - I like this - trying to have course objectives get the same treatment as learning materials with this PR.

created introduction section on course_objectives.md

---

courses-and-sessions/courses/course_objectives.md

```
On branch fix_text_in_introduction_course_objectives
```

fixed typo in introduction section on course_objectives.md

---

courses-and-sessions/courses/course_objectives.md

```
On branch add_link_to_objective_definition_course_obj_level
```
This may not actually work due to how `definition` works. Either the link may not work or there are too many characters involved due to the URL. May end up reverting but need to try this out for future page updates here and in other places.

attempting to add link to crs obj definition

---

courses-and-sessions/courses/course_objectives.md

```
On branch edit_link_to_objective_definition_course_obj_level
```
This is only a test and will be reverted. The previous PR #696 never seemed to get processed so I added some nonsense here to make sure changes are being pushed out.

attempting to add link to crs obj definition only a test

---

courses-and-sessions/courses/course_objectives.md

```
On branch edit_link_to_objective_definition_course_obj_level_update
```
Changed one word "may" to "can" - why are the updates not getting pushed?

attempting to edit link to crs obj definition

---

courses-and-sessions/courses/course_objectives.md

```                                                           
On branch add_link_to_objective_definition_course_obj_level_redux
```
Straight up added "link" to the end of the "definition" of objective - need to see if this is possible - changes are being pushed - I know this because of the previous PR changing "may" to "can" did get pushed through.

attempting to edit link to crs obj definition again

---

courses-and-sessions/courses/course_objectives.md

```                                                      
On branch remove_link_didnt_work
```
The title says it all. I guess if I want to use the cool buttons that get provided when there is no text on the main page but there is a short introduction (which doesn't seem to allow links for some reason), I will have to put the links elsewhere.

removed link that didnt work - lame

---

schools/vocabularies.md

```
On branch fix_program_year_link_in_school_vocabularies
modified:   schools/vocabularies.md
```
I realized that the link pointing to program years from within the schools/vocabularies.md file was not pointing correctly to the root of program years. This PR fixes that.

updated link in school vocab for program years - point to root

---

dashboard/materials-view.md

```
On branch fix_link_to_activity_check_boxes_materials-view.md
modified:   dashboard/materials-view.md
```
The link on this page to demonstrate the learning materials activity check boxes as they pertain to event detail was basically a circular loop taking the user basically nowhere. This PR fixes that.

updated link in dashboard materials view to activity check boxes

---

admin/user-account-and-role-management.md

```
On branch make_sure_secondary_cohort_added_first
modified:   admin/user-account-and-role-management.md
```
I added a note to the page listed above to advise that newly added cohorts are always added as secondary cohorts and need to be promoted to primary status if that is the case.

updated cohort assignment process in admin console

---

courses-and-sessions/sessions/README.md

There was no reason to have a link to take the reader to a different location to read the same information - link removed - description of session kept as is.

removed link to glossary since target was same as text

---

courses-and-sessions/sessions/README.md

```                                                         
On branch fix_typo_in_NOTE_regarding_optional_session_attributes
```

optional session attributes - typo fixed

---

courses-and-sessions/sessions/README.md

```                                    
On branch fix_up_a_couple_verbose_captions
```
* A couple of headings were far too long with brackets and other stuff that needed to be shortened 
* added a link to schools >> session attributes for instructions on customizing those fields

optional session attributes - cleaned up and added link

---

dashboard/icons-explained.md

I removed an erroneous double extension in the file path.

fix missing image on Icons Explained page

---

courses-and-sessions/README.md

```
On branch fix_typo_plural_needed
modified:   courses-and-sessions/README.md
```

quick typo fix plural form of noun missing

---

glossary.md

```
On branch fix_typo_scheduled_tba_glossary
```

fixed typo "as" instead of "at"

---

dashboard/event-detail-view.md

```                                                              
On branch caption_update
modified:   dashboard/event-detail-view.md
```
The caption "Updated Event Detail" was not really applicable because the text section has nothing to do with "updated" in this case. This PR fixes that.

updated caption to event detail not updated since not applicable

---

courses-and-sessions/courses/competencies.md

```
On branch more_work_on_competencies_course_level
```
The course competency page is still hidden - added a link to the school competency setup.

added link to school competencies setup

---

courses-and-sessions/courses/competencies.md

```
On branch more_work_on_competencies_course_level_fix_prev
```
This fixes the text entered and added in #786 which was factually inaccurate. Only competencies that have been actually mapped to program year objectives and course objectives are actually displayed on the course page.

added a bit more descriptive text on competency fixed

---

dashboard/README.md

Added a spiel to the `dashboard/README.md` page - it needed to be pointed out that the help link to the user guide is always available - in any screen size.

added a bit of text for description of help link

---

dashboard/README.md
dashboard/icons-explained.md

* on branch `icons_explained_caps_fix`
* files modified - `README.md`, `icons-explained.md`
* changed link to "here" for more information 
* undid changes from #811 since there now appears to be a vertical spacing issue = too much space all over the guide

updated link to .ics feed

---

learner-groups/README.md

The `README` file indicated that in order to be associated with an event, a learner HAD to be a member of a learner group. This is no longer true since individual learners can be associated with / attached to learning events. This PR removes that reference correctly.

learners can be individually attached to offerings

---

learner-groups/edit-group-properties/edit-group-membership.md

```
On branch fix_previous_PR_link_new_image
modified:   learner-groups/edit-group-properties/edit-group-membership.md
```
The previous PR #830 replaced an image which did not appear in the guide - I am hoping this will fix that as I have not seen this before.

image missing from previous PR - fixing here hopefully

---

learner-groups/edit-group-properties/edit-group-membership.md
learner-groups/sub-groups.md

```
On branch fix_typo_add_link_lg_membership_edit
modified:   learner-groups/edit-group-properties/edit-group-membership.md
modified:   learner-groups/sub-groups.md
```

fixed typo - added link to edit instructions

---

learner-groups/remove-learner-group.md

```
On branch one_more_comment_on_learner_group_removal
modified:   learner-groups/remove-learner-group.md
```
Text added to the above-mentioned file that advises that if even if sub groups have membership, as long as there are no offerings or ILM's attached (published or not), the learner group and any subs can still be deleted / removed from the system.

minor text update

---

learner-groups/learner-group-defaults.md

```
On branch checkout_spelling_of_accommodation
modified:   learner-groups/learner-group-defaults.md
```
Two m's needed in addition to two c's in long word "accommodation" - this PR fixes this.

minor text update fixed spelling of accommodation

---

courses-and-sessions/offerings/README.md

```
On branch update_small_group_offerings_require_lg
modified:   courses-and-sessions/offerings/README.md
```
It needed to be pointed out that small groups have learner group as required field. Individual offerings can be saved without learner group or learner attachment. This information can be added later. This PR adds that informational tidbit.

added mention of requirement of learner groups for small grp offering

---

dashboard/calendar-search-and-filter-options.md

```
On branch remove_most_of_misleading_section_on_calendar_options
```
There is no longer an Academic Year selector at the top of the calendar. Users can pick courses from different academic years but the selector is not a part of the interface. I don't recall when it was. Anyway this PR removes a bunch of older references that don't seem to be applicable anymore and attempts to clear this up.

removed a few things from olden times

---

dashboard/calendar-view.md

```
On branch get_rid_of_duplicate_calendar_view_label
modified:   dashboard/calendar-view.md
```
This PR also removes the "with the advent of 3.x no CSS override not permitted but maybe someday" reference.

chapter adjustment calendar view remove dupe

---

courses-and-sessions/courses/view-learning-materials.md

```
On branch another_quick_disclaimer_course_lm_viewing
```
I found this out the hard way - and this applies to viewing LM's in Courses and Sessions >> Course details as well, if you click the view button for a .pdf and then close that window, you will need to re-open Ilios - kind of a pain.

added a bit more text - open .pdf preview course LM disclaimer

---

glossary.md

```
On branch remove_curricular_object_from_glossary
```
I ended not removing, but enhancing, the description of curricular object in the glossary - bad branch name.

added a bit more info about curricular object in glossary

---

courses-and-sessions/courses/README.md

```
On branch one_more_update_to_course_MeSH_text
```
Redundant verbiage removed to match other text fixed in #983

course MeSH description updated

---

dashboard/README.md

```
On branch start_process_of_navigation_menu_not_flyout
```

fixing verbiage of Ilios menu - navigation not flyout

---

dashboard/README.md

```
On branch one_more_quick_text_add_for_clarification
```

fixing verbiage of Ilios menu - navigation not flyout -text add

---

dashboard/README.md

Working on changing guide to reflect "Navigation" menu rather than "Flyout" menu. Removed an unnecessary instance of "Flyout", which is now out of context and confusing.
On branch `fix_link_nav_rather_than_flyout_menu`

fixing verbiage of Ilios menu - navigation not flyout -text rmvd

---

README.md

```
On branch add_bit_about_clicking_on_guide_images
```
* Images can be clicked in the user guide to allow for closer inspection by the reader. This PR adds that information to the guide.
* Cleaned up a bit on the breadcrumbs section added in #1019

introduction needs work - added bit about clickable images

---

dashboard/README.md

```
On branch update_student_advisor_menu_view
```
This PR addresses the fact that users who are assigned a Student Advisor role do not see the Ilios Navigation Menu unless they have been assigned a higher role in the system such as Instructor, Director, or Administrator.

dashboard README update - student advisor role

---

dashboard/icons-explained.md

Re-arranged the `icons-explained.md` page a bit and added a bit more information for better clarify.

icons explained page re-organized a bit and a few additions

---

dashboard/materials-view.md

```
On branch update_check_box_desription_lm_needs_more_work
modified:   dashboard/materials-view.md
```
I changed the wording since I found the previous information to be inaccurate and misleading. The check box activity is not "shared" - only the logged-in user sees this but will see it throughout the application where learning materials are tracked and displayed. This PR fixes that.

added bit about how check boxes on user basis

---

README.md

```
On branch match_caps_user_guide
```
Capitalization of "user guide" matched up in Contact Info section.

user guide caps needed to match

---

courses-and-sessions/sessions/edit-session.md

```
On branch for_now_add_link_to_session_vocab_maint_caption_update
```
The link to Manage Session Term(s) wasn't working as well as I had hoped since I was linking from Courses over to Sessions - this PR simplifies the link to hopefully make it be more anchored. We'll see. A follow-up PR to this one will be required once this change shows up.

added link to vocab term session level caption change

---

courses-and-sessions/courses/README.md

The link on `courses/README.md` was incorrectly pointing to schools - this is regarding course vocabulary terms - new page was added recently so this link needed to be updated.

fixed link to course terms rather than school setup

---

reports/curriculum_reports.md

```
On branch update_reports_curriculum_reports_output_fields
modified:   reports/curriculum_reports.md
```
More is coming regarding this update - this sets up the place to put the .csv file download fields of the current Curriculum Reports.

added output summary description to curriculum reports page

---

reports/curriculum_reports.md

The date of the starting point for curriculum reports was incorrectly stated as "2024" - this PR fixes that and makes it correctly indicated as "2025" - quick fix.

wrong year indicated in curriculum reports

---

reports/curriculum_reports.md

There was an image that was accidentally duplicated. This was not intended - this PR fixes that hasty error.

get rid of duplicated image - results summmary

---

courses-and-sessions/README.md

To match the listing of the chapter along with the captions we use in Ilios for the course-level configurable options, this chapter caption needed to be updated to match.

leadership all that is needed for chapter listing

---

README.md

```
On branch try_some_fomatting_for_user_guide_breadcrumb_info
```
This may end up being a disaster but I wanted to try it anyway - trying to make the breadcrumb link descriptions match their actual appearance.

this is a test - trying some color formatting

---

README.md

```
On branch use_bold_for_now_colors_not_working
```
Reverting the code back to simply add **bold** to the breadcrumb link examples - I wanted Ilios orange coloring applied but for today will settle for simply bold. This PR cleans up the code.

this is a test - bold yes - colors no

---

courses-and-sessions/offerings/README.md

```
On branch eliminate_now_from_text_not_needed
modified:   courses-and-sessions/offerings/README.md
```
Updating this offering section in general, I noticed the phrase "now" appearing where it is not needed anymore - the entire section will be updated soon.

removed now from a statement where it is no longer valid

---

courses-and-sessions/sessions/add-new-session.md

Related to #1194 in that this is on the same page and is also a typo - although in this case there was a space missing - this PR fixes that.

fixed typo - new session page spacing missing

---

learner-groups/sub-groups.md

```
On branch add_bit_about_the_+_icon_disappearing_lg_mgmt
modified:   learner-groups/sub-groups.md
```
I added the bit to explain this in the edit membership section of learner group management. It could be added also to remove learners section but for now, this PR at least adds it into the guide.

add or remove buttons disappear when using check boxes

---

programs/edit-program.md

```
On branch update_edit_title_program_year_to_match
modified:   programs/edit-program.md
```
This was actually an update to "programs" not "program year" - branch not named correctly in this case.

fixed links to match destinations

---

programs/edit_program_year.md

```
On branch explain_mapping_from_program_year_to_competency
modified:   programs/edit_program_year.md
```
The updated list did not show up but hopefully this PR will push that and another minor change through to get things going. More documentation on mapping competencies is in progress here.

more new images - competency list updated

---

reports/subject_reports.md

Added a description of how subject reports can be saved and are available to the logged-in user at any time and how curriculum reports are created at run time but can be shared. More details coming up about the sharing of these reports.

added a link and some text to subject reports

---

SUMMARY.md
courses-and-sessions/courses/MeSH_terms.md

```
On branch create_page_for_course_MeSH
new file:   courses-and-sessions/courses/MeSH_terms.md
```
This PR creates the page for course level MeSH - MeSH is covered in the guide but not explicitly at the course level. That will be done upcoming. The MeSH page is linked in the initial text of the page. Link added to summary.md to create the chapter.

added page and added link course MeSH

---

courses-and-sessions/courses/MeSH_terms.md

Shortened the temporary introduction spiel on recently created course MeSH page. More is coming soon but that reference was not necessary in the guide since a link was provided for reference to MeSH for now.

added page and added link course MeSH update
